// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/bme/v1/events.proto

package v1

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventCircuitBreakerStatusChange is emitted when circuit breaker status changes
type EventMintStatusChange struct {
	// previous_status is the previous status
	PreviousStatus MintStatus `protobuf:"varint,1,opt,name=previous_status,json=previousStatus,proto3,enum=akash.bme.v1.MintStatus" json:"previous_status,omitempty"`
	// new_status is the new status
	NewStatus MintStatus `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=akash.bme.v1.MintStatus" json:"new_status,omitempty"`
	// collateral_ratio is the CR that triggered the change
	CollateralRatio cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=collateral_ratio,json=collateralRatio,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"collateral_ratio"`
}

func (m *EventMintStatusChange) Reset()         { *m = EventMintStatusChange{} }
func (m *EventMintStatusChange) String() string { return proto.CompactTextString(m) }
func (*EventMintStatusChange) ProtoMessage()    {}
func (*EventMintStatusChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_9866c556a255df13, []int{0}
}
func (m *EventMintStatusChange) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventMintStatusChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventMintStatusChange.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventMintStatusChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMintStatusChange.Merge(m, src)
}
func (m *EventMintStatusChange) XXX_Size() int {
	return m.Size()
}
func (m *EventMintStatusChange) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMintStatusChange.DiscardUnknown(m)
}

var xxx_messageInfo_EventMintStatusChange proto.InternalMessageInfo

func (m *EventMintStatusChange) GetPreviousStatus() MintStatus {
	if m != nil {
		return m.PreviousStatus
	}
	return MintStatusUnspecified
}

func (m *EventMintStatusChange) GetNewStatus() MintStatus {
	if m != nil {
		return m.NewStatus
	}
	return MintStatusUnspecified
}

// EventVaultFunded is emitted when the vault is seeded with AKT
type EventVaultFunded struct {
	// amount is the AKT amount added to vault
	Amount types.Coin `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount"`
	// source is where the funds came from
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// new_vault_balance is the new vault balance
	NewVaultBalance types.Coin `protobuf:"bytes,3,opt,name=new_vault_balance,json=newVaultBalance,proto3" json:"new_vault_balance"`
}

func (m *EventVaultFunded) Reset()         { *m = EventVaultFunded{} }
func (m *EventVaultFunded) String() string { return proto.CompactTextString(m) }
func (*EventVaultFunded) ProtoMessage()    {}
func (*EventVaultFunded) Descriptor() ([]byte, []int) {
	return fileDescriptor_9866c556a255df13, []int{1}
}
func (m *EventVaultFunded) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventVaultFunded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventVaultFunded.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventVaultFunded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventVaultFunded.Merge(m, src)
}
func (m *EventVaultFunded) XXX_Size() int {
	return m.Size()
}
func (m *EventVaultFunded) XXX_DiscardUnknown() {
	xxx_messageInfo_EventVaultFunded.DiscardUnknown(m)
}

var xxx_messageInfo_EventVaultFunded proto.InternalMessageInfo

func (m *EventVaultFunded) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func (m *EventVaultFunded) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *EventVaultFunded) GetNewVaultBalance() types.Coin {
	if m != nil {
		return m.NewVaultBalance
	}
	return types.Coin{}
}

// EventLedgerRecordExecuted emitted information of burn/mint event of token A burn to mint token B
type EventLedgerRecordExecuted struct {
	// burned_from source address of the tokens burned
	ID LedgerRecordID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
	// burned_from source address of the tokens burned
	BurnedFrom string `protobuf:"bytes,2,opt,name=burned_from,json=burnedFrom,proto3" json:"burned_from" yaml:"burned_from"`
	// minted_to destination address of the tokens minted
	MintedTo string `protobuf:"bytes,3,opt,name=minted_to,json=mintedTo,proto3" json:"minted_to" yaml:"minted_to"`
	// module is module account performing burn
	Burner string `protobuf:"bytes,4,opt,name=burner,proto3" json:"burner" yaml:"burner"`
	// module is module account performing mint
	Minter string `protobuf:"bytes,5,opt,name=minter,proto3" json:"minter" yaml:"minter"`
	// burned is the coin burned at price
	Burned *CoinPrice `protobuf:"bytes,6,opt,name=burned,proto3" json:"burned" yaml:"burned"`
	// minted is coin minted at price
	Minted              *CoinPrice `protobuf:"bytes,7,opt,name=minted,proto3" json:"minted" yaml:"minted"`
	Spread              types.Coin `protobuf:"bytes,8,opt,name=spread,proto3" json:"spread" yaml:"spread"`
	RemintCreditIssued  *CoinPrice `protobuf:"bytes,9,opt,name=remint_credit_issued,json=remintCreditIssued,proto3" json:"remint_credit_issued" yaml:"remint_credit_issued"`
	RemintCreditAccrued *CoinPrice `protobuf:"bytes,10,opt,name=remint_credit_accrued,json=remintCreditAccrued,proto3" json:"remint_credit_accrued" yaml:"remint_credit_accrued"`
}

func (m *EventLedgerRecordExecuted) Reset()         { *m = EventLedgerRecordExecuted{} }
func (m *EventLedgerRecordExecuted) String() string { return proto.CompactTextString(m) }
func (*EventLedgerRecordExecuted) ProtoMessage()    {}
func (*EventLedgerRecordExecuted) Descriptor() ([]byte, []int) {
	return fileDescriptor_9866c556a255df13, []int{2}
}
func (m *EventLedgerRecordExecuted) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventLedgerRecordExecuted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventLedgerRecordExecuted.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventLedgerRecordExecuted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventLedgerRecordExecuted.Merge(m, src)
}
func (m *EventLedgerRecordExecuted) XXX_Size() int {
	return m.Size()
}
func (m *EventLedgerRecordExecuted) XXX_DiscardUnknown() {
	xxx_messageInfo_EventLedgerRecordExecuted.DiscardUnknown(m)
}

var xxx_messageInfo_EventLedgerRecordExecuted proto.InternalMessageInfo

func (m *EventLedgerRecordExecuted) GetID() LedgerRecordID {
	if m != nil {
		return m.ID
	}
	return LedgerRecordID{}
}

func (m *EventLedgerRecordExecuted) GetBurnedFrom() string {
	if m != nil {
		return m.BurnedFrom
	}
	return ""
}

func (m *EventLedgerRecordExecuted) GetMintedTo() string {
	if m != nil {
		return m.MintedTo
	}
	return ""
}

func (m *EventLedgerRecordExecuted) GetBurner() string {
	if m != nil {
		return m.Burner
	}
	return ""
}

func (m *EventLedgerRecordExecuted) GetMinter() string {
	if m != nil {
		return m.Minter
	}
	return ""
}

func (m *EventLedgerRecordExecuted) GetBurned() *CoinPrice {
	if m != nil {
		return m.Burned
	}
	return nil
}

func (m *EventLedgerRecordExecuted) GetMinted() *CoinPrice {
	if m != nil {
		return m.Minted
	}
	return nil
}

func (m *EventLedgerRecordExecuted) GetSpread() types.Coin {
	if m != nil {
		return m.Spread
	}
	return types.Coin{}
}

func (m *EventLedgerRecordExecuted) GetRemintCreditIssued() *CoinPrice {
	if m != nil {
		return m.RemintCreditIssued
	}
	return nil
}

func (m *EventLedgerRecordExecuted) GetRemintCreditAccrued() *CoinPrice {
	if m != nil {
		return m.RemintCreditAccrued
	}
	return nil
}

// EventLedgerRecordCanceled emitted information of unsuccessful burn/mint event
type EventLedgerRecordCanceled struct {
	// burned_from source address of the tokens burned
	ID LedgerRecordID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
	// fail_reason
	CancelReason LedgerCanceledRecord_BMCancelReason `protobuf:"varint,2,opt,name=cancel_reason,json=cancelReason,proto3,enum=akash.bme.v1.LedgerCanceledRecord_BMCancelReason" json:"cancel_reason" yaml:"cancel_reason"`
	// owner source of the coins to be burned
	Owner string `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner" yaml:"owner"`
	// to destination of the minted coins.
	// if minted coin is ACT, "to" must be same as signer
	To string `protobuf:"bytes,4,opt,name=to,proto3" json:"to" yaml:"to"`
	// coins_to_burn
	CoinsToBurn types.Coin `protobuf:"bytes,5,opt,name=coins_to_burn,json=coinsToBurn,proto3" json:"coins_to_burn" yaml:"coins_to_burn"`
	// denom_to_mint
	DenomToMint string `protobuf:"bytes,6,opt,name=denom_to_mint,json=denomToMint,proto3" json:"denom_to_mint" yaml:"denom_to_mint"`
}

func (m *EventLedgerRecordCanceled) Reset()         { *m = EventLedgerRecordCanceled{} }
func (m *EventLedgerRecordCanceled) String() string { return proto.CompactTextString(m) }
func (*EventLedgerRecordCanceled) ProtoMessage()    {}
func (*EventLedgerRecordCanceled) Descriptor() ([]byte, []int) {
	return fileDescriptor_9866c556a255df13, []int{3}
}
func (m *EventLedgerRecordCanceled) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventLedgerRecordCanceled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventLedgerRecordCanceled.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventLedgerRecordCanceled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventLedgerRecordCanceled.Merge(m, src)
}
func (m *EventLedgerRecordCanceled) XXX_Size() int {
	return m.Size()
}
func (m *EventLedgerRecordCanceled) XXX_DiscardUnknown() {
	xxx_messageInfo_EventLedgerRecordCanceled.DiscardUnknown(m)
}

var xxx_messageInfo_EventLedgerRecordCanceled proto.InternalMessageInfo

func (m *EventLedgerRecordCanceled) GetID() LedgerRecordID {
	if m != nil {
		return m.ID
	}
	return LedgerRecordID{}
}

func (m *EventLedgerRecordCanceled) GetCancelReason() LedgerCanceledRecord_BMCancelReason {
	if m != nil {
		return m.CancelReason
	}
	return BMCancelReasonUnknown
}

func (m *EventLedgerRecordCanceled) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *EventLedgerRecordCanceled) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *EventLedgerRecordCanceled) GetCoinsToBurn() types.Coin {
	if m != nil {
		return m.CoinsToBurn
	}
	return types.Coin{}
}

func (m *EventLedgerRecordCanceled) GetDenomToMint() string {
	if m != nil {
		return m.DenomToMint
	}
	return ""
}

func init() {
	proto.RegisterType((*EventMintStatusChange)(nil), "akash.bme.v1.EventMintStatusChange")
	proto.RegisterType((*EventVaultFunded)(nil), "akash.bme.v1.EventVaultFunded")
	proto.RegisterType((*EventLedgerRecordExecuted)(nil), "akash.bme.v1.EventLedgerRecordExecuted")
	proto.RegisterType((*EventLedgerRecordCanceled)(nil), "akash.bme.v1.EventLedgerRecordCanceled")
}

func init() { proto.RegisterFile("akash/bme/v1/events.proto", fileDescriptor_9866c556a255df13) }

var fileDescriptor_9866c556a255df13 = []byte{
	// 946 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcf, 0x6f, 0x13, 0x47,
	0x14, 0xce, 0xba, 0xc1, 0xe0, 0x71, 0x42, 0xd2, 0x69, 0x68, 0x37, 0x81, 0x7a, 0xd0, 0x9e, 0xa8,
	0x2a, 0xd6, 0x32, 0x54, 0xa2, 0x2d, 0xe5, 0x90, 0x8d, 0xa1, 0x8a, 0x02, 0x12, 0x5a, 0x22, 0x0e,
	0x15, 0xea, 0x6a, 0xbc, 0x33, 0x75, 0x56, 0xf1, 0xee, 0x58, 0x33, 0xb3, 0x4e, 0xa3, 0x9e, 0x7a,
	0xe9, 0xa1, 0xa7, 0xfe, 0x29, 0x3d, 0xf0, 0x47, 0xe4, 0x52, 0x09, 0x71, 0xaa, 0x7a, 0x18, 0x55,
	0xc9, 0xcd, 0xb7, 0xfa, 0x2f, 0xa8, 0xe6, 0x47, 0xf0, 0x1a, 0x39, 0x86, 0x03, 0x37, 0xbf, 0xef,
	0xbd, 0xef, 0x9b, 0xef, 0xbd, 0xdd, 0x37, 0x6b, 0xb0, 0x89, 0x0f, 0xb1, 0x38, 0x68, 0xf7, 0x72,
	0xda, 0x1e, 0x75, 0xda, 0x74, 0x44, 0x0b, 0x29, 0xc2, 0x21, 0x67, 0x92, 0xc1, 0x15, 0x93, 0x0a,
	0x7b, 0x39, 0x0d, 0x47, 0x9d, 0xad, 0x8d, 0x3e, 0xeb, 0x33, 0x93, 0x68, 0xeb, 0x5f, 0xb6, 0x66,
	0x6b, 0x33, 0x65, 0x22, 0x67, 0x22, 0xb1, 0x09, 0x1b, 0xb8, 0x54, 0xcb, 0x46, 0xed, 0x1e, 0x16,
	0x5a, 0xbb, 0x47, 0x25, 0xee, 0xb4, 0x53, 0x96, 0x15, 0x2e, 0xef, 0xcf, 0x9c, 0x2c, 0x8f, 0x87,
	0xd4, 0x31, 0x83, 0xff, 0x3c, 0x70, 0xed, 0xa1, 0x76, 0xf2, 0x24, 0x2b, 0xe4, 0x33, 0x89, 0x65,
	0x29, 0x76, 0x0e, 0x70, 0xd1, 0xa7, 0x70, 0x1b, 0xac, 0x0d, 0x39, 0x1d, 0x65, 0xac, 0x14, 0x89,
	0x30, 0x09, 0xdf, 0xbb, 0xe9, 0xdd, 0xba, 0x7a, 0xc7, 0x0f, 0xab, 0x66, 0xc3, 0x29, 0x31, 0xbe,
	0x7a, 0x4e, 0xb0, 0x31, 0xbc, 0x07, 0x40, 0x41, 0x8f, 0xce, 0xd9, 0xb5, 0x77, 0xb0, 0x1b, 0x05,
	0x3d, 0x72, 0xc4, 0x17, 0x60, 0x3d, 0x65, 0x83, 0x01, 0x96, 0x94, 0xe3, 0x41, 0xc2, 0xb1, 0xcc,
	0x98, 0xff, 0xd1, 0x4d, 0xef, 0x56, 0x23, 0xea, 0x9c, 0x28, 0xb4, 0xf4, 0x8f, 0x42, 0xd7, 0x6d,
	0xc7, 0x82, 0x1c, 0x86, 0x19, 0x6b, 0xe7, 0x58, 0x1e, 0x84, 0x8f, 0x69, 0x1f, 0xa7, 0xc7, 0x5d,
	0x9a, 0xbe, 0x7e, 0x79, 0x1b, 0xb8, 0xf1, 0x74, 0x69, 0x1a, 0xaf, 0x4d, 0xa5, 0x62, 0xad, 0x14,
	0xfc, 0xe9, 0x81, 0x75, 0xd3, 0xf3, 0x73, 0x5c, 0x0e, 0xe4, 0xa3, 0xb2, 0x20, 0x94, 0xc0, 0x7b,
	0xa0, 0x8e, 0x73, 0x56, 0x16, 0xd2, 0x74, 0xd9, 0xbc, 0xb3, 0x19, 0x3a, 0x09, 0x3d, 0xd3, 0xd0,
	0xcd, 0x34, 0xdc, 0x61, 0x59, 0x11, 0x2d, 0x6b, 0x0f, 0xb1, 0x2b, 0x87, 0x9f, 0x82, 0xba, 0x60,
	0x25, 0x4f, 0xa9, 0x69, 0xb0, 0x11, 0xbb, 0x08, 0xee, 0x81, 0x8f, 0x75, 0xf3, 0x23, 0x7d, 0x46,
	0xd2, 0xc3, 0x03, 0x5c, 0xa4, 0xd4, 0x34, 0xf1, 0x1e, 0xda, 0x6b, 0x05, 0x3d, 0x32, 0xe6, 0x22,
	0xcb, 0x0b, 0x4e, 0x2e, 0x83, 0x4d, 0x63, 0xf9, 0x31, 0x25, 0x7d, 0xca, 0x63, 0x9a, 0x32, 0x4e,
	0x1e, 0xfe, 0x4c, 0xd3, 0x52, 0x52, 0x02, 0xf7, 0x40, 0x2d, 0x23, 0xce, 0xf7, 0x8d, 0xd9, 0xf9,
	0x56, 0xeb, 0x77, 0xbb, 0xd1, 0xe7, 0x5a, 0xfe, 0x54, 0xa1, 0xda, 0x6e, 0x77, 0xac, 0x50, 0x2d,
	0x23, 0x13, 0x85, 0x1a, 0xc7, 0x38, 0x1f, 0x7c, 0x1b, 0x64, 0x24, 0x88, 0x6b, 0x19, 0x81, 0x3f,
	0x82, 0x66, 0xaf, 0xe4, 0x05, 0x25, 0xc9, 0x4f, 0x9c, 0xe5, 0xb6, 0xa9, 0xe8, 0xc1, 0x58, 0xa1,
	0x2a, 0x3c, 0x51, 0x08, 0x5a, 0x5a, 0x05, 0x0c, 0x5e, 0xbf, 0xbc, 0xbd, 0xe1, 0x3a, 0xdb, 0x26,
	0x84, 0x53, 0x21, 0x9e, 0x49, 0x9e, 0x15, 0xfd, 0x18, 0xd8, 0xaa, 0x47, 0x9c, 0xe5, 0xf0, 0x39,
	0x68, 0xe4, 0x59, 0x21, 0x29, 0x49, 0xe4, 0xf9, 0x43, 0xfd, 0x66, 0xac, 0xd0, 0x14, 0x9c, 0x28,
	0xb4, 0x6e, 0xb5, 0xdf, 0x40, 0x17, 0x2b, 0x5f, 0xb1, 0x35, 0xfb, 0x0c, 0xee, 0x81, 0xba, 0x39,
	0x85, 0xfb, 0xcb, 0x46, 0xf4, 0xee, 0x58, 0x21, 0x87, 0x4c, 0x14, 0x5a, 0xad, 0xb8, 0xe5, 0x17,
	0xcb, 0x39, 0x82, 0x16, 0x33, 0xc2, 0xdc, 0xbf, 0x34, 0x15, 0xb3, 0xc8, 0x54, 0xcc, 0xc6, 0x0b,
	0xc4, 0x6c, 0x01, 0x7c, 0xea, 0x9c, 0x11, 0xbf, 0x6e, 0x1e, 0xd1, 0x67, 0xb3, 0x8f, 0x48, 0x3f,
	0xf7, 0xa7, 0x3c, 0x4b, 0x69, 0x84, 0x4e, 0x14, 0xf2, 0xde, 0xd8, 0x26, 0x6f, 0xd9, 0x26, 0x81,
	0xb3, 0x47, 0xb4, 0xa2, 0xed, 0xdb, 0xbf, 0xfc, 0x9e, 0x8a, 0xb6, 0xfc, 0x2d, 0xef, 0x5a, 0xd1,
	0xfe, 0x80, 0x31, 0xa8, 0x8b, 0x21, 0xa7, 0x98, 0xf8, 0x57, 0xde, 0xf5, 0x8a, 0x6a, 0xcd, 0x25,
	0xad, 0x69, 0x09, 0x53, 0x4d, 0x1b, 0x07, 0xb1, 0x4b, 0xc0, 0xdf, 0x3c, 0xb0, 0xc1, 0xa9, 0x3e,
	0x20, 0x49, 0x39, 0x25, 0x99, 0x4c, 0x32, 0x21, 0x4a, 0x4a, 0xfc, 0xc6, 0x62, 0xd3, 0xf7, 0x9d,
	0xe9, 0xb9, 0xe4, 0x89, 0x42, 0xd7, 0xed, 0x71, 0xf3, 0xb2, 0x41, 0x0c, 0x2d, 0xbc, 0x63, 0xd0,
	0x5d, 0x03, 0xc2, 0xdf, 0x3d, 0x70, 0x6d, 0xb6, 0x1a, 0xa7, 0x29, 0xd7, 0x4e, 0xc0, 0x62, 0x27,
	0x0f, 0x9c, 0x93, 0xf9, 0xec, 0x89, 0x42, 0x37, 0xe6, 0x59, 0x71, 0xe9, 0x20, 0xfe, 0xa4, 0xea,
	0x65, 0xdb, 0xa1, 0x7f, 0x2d, 0xcf, 0x59, 0xe5, 0x1d, 0xbd, 0xe5, 0x83, 0x0f, 0xbd, 0xca, 0xbf,
	0x7a, 0x60, 0x35, 0x35, 0xca, 0x09, 0xa7, 0x58, 0xb0, 0xc2, 0xdd, 0xc1, 0x9d, 0x79, 0xc2, 0xe7,
	0x16, 0xec, 0x01, 0x61, 0xf4, 0xc4, 0x02, 0xb1, 0x21, 0x46, 0x5f, 0x8c, 0x15, 0x9a, 0xd5, 0x9a,
	0x28, 0xb4, 0x61, 0x8f, 0x9b, 0x81, 0x83, 0x78, 0x25, 0xad, 0x10, 0xe1, 0xf7, 0xe0, 0x12, 0x3b,
	0xd2, 0x5b, 0xe9, 0xee, 0xef, 0xb1, 0x42, 0x16, 0x98, 0x28, 0xb4, 0x62, 0xf9, 0x26, 0xbc, 0x78,
	0x8d, 0x6c, 0x39, 0xbc, 0x0f, 0x6a, 0x92, 0xb9, 0xdd, 0xfe, 0x52, 0x77, 0x6c, 0x6e, 0x0a, 0xd7,
	0xf1, 0xa2, 0x2b, 0xa2, 0x26, 0x19, 0xfc, 0x05, 0xac, 0xea, 0xcf, 0xa1, 0x48, 0x24, 0x4b, 0xf4,
	0x0e, 0x99, 0xb5, 0x5e, 0xf8, 0x96, 0x7f, 0xe7, 0xc6, 0xdb, 0xd4, 0x91, 0xd8, 0x67, 0x51, 0xc9,
	0x0b, 0x33, 0x83, 0xaa, 0x4c, 0x65, 0x06, 0x55, 0x38, 0x88, 0x9b, 0xe9, 0x94, 0x05, 0x5f, 0x80,
	0x55, 0x42, 0x0b, 0x96, 0xeb, 0xb4, 0x7e, 0x1f, 0xcc, 0x35, 0xd0, 0x88, 0xbe, 0xd6, 0xea, 0x5d,
	0x9d, 0xd8, 0x67, 0xfa, 0x33, 0xa8, 0xd5, 0x67, 0xea, 0xa6, 0xea, 0x33, 0x70, 0x10, 0x37, 0xc9,
	0x94, 0x15, 0x7d, 0x75, 0x72, 0xda, 0xf2, 0x5e, 0x9d, 0xb6, 0xbc, 0x7f, 0x4f, 0x5b, 0xde, 0x1f,
	0x67, 0xad, 0xa5, 0x57, 0x67, 0xad, 0xa5, 0xbf, 0xcf, 0x5a, 0x4b, 0x3f, 0x6c, 0x0d, 0x0f, 0xfb,
	0x21, 0x3e, 0x94, 0x21, 0xa1, 0xa3, 0x76, 0x9f, 0xb5, 0x0b, 0x46, 0xa8, 0xfb, 0x0f, 0xd0, 0xab,
	0x9b, 0xcf, 0xff, 0xdd, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x40, 0xb0, 0x2f, 0xe6, 0x94, 0x08,
	0x00, 0x00,
}

func (m *EventMintStatusChange) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventMintStatusChange) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventMintStatusChange) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.CollateralRatio.Size()
		i -= size
		if _, err := m.CollateralRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.NewStatus != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.NewStatus))
		i--
		dAtA[i] = 0x10
	}
	if m.PreviousStatus != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.PreviousStatus))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventVaultFunded) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventVaultFunded) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventVaultFunded) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.NewVaultBalance.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Source) > 0 {
		i -= len(m.Source)
		copy(dAtA[i:], m.Source)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Source)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventLedgerRecordExecuted) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventLedgerRecordExecuted) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventLedgerRecordExecuted) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RemintCreditAccrued != nil {
		{
			size, err := m.RemintCreditAccrued.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvents(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x52
	}
	if m.RemintCreditIssued != nil {
		{
			size, err := m.RemintCreditIssued.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvents(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	{
		size, err := m.Spread.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if m.Minted != nil {
		{
			size, err := m.Minted.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvents(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.Burned != nil {
		{
			size, err := m.Burned.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvents(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if len(m.Minter) > 0 {
		i -= len(m.Minter)
		copy(dAtA[i:], m.Minter)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Minter)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Burner) > 0 {
		i -= len(m.Burner)
		copy(dAtA[i:], m.Burner)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Burner)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.MintedTo) > 0 {
		i -= len(m.MintedTo)
		copy(dAtA[i:], m.MintedTo)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.MintedTo)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BurnedFrom) > 0 {
		i -= len(m.BurnedFrom)
		copy(dAtA[i:], m.BurnedFrom)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.BurnedFrom)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventLedgerRecordCanceled) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventLedgerRecordCanceled) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventLedgerRecordCanceled) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DenomToMint) > 0 {
		i -= len(m.DenomToMint)
		copy(dAtA[i:], m.DenomToMint)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.DenomToMint)))
		i--
		dAtA[i] = 0x32
	}
	{
		size, err := m.CoinsToBurn.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.To) > 0 {
		i -= len(m.To)
		copy(dAtA[i:], m.To)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.To)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x1a
	}
	if m.CancelReason != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.CancelReason))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventMintStatusChange) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PreviousStatus != 0 {
		n += 1 + sovEvents(uint64(m.PreviousStatus))
	}
	if m.NewStatus != 0 {
		n += 1 + sovEvents(uint64(m.NewStatus))
	}
	l = m.CollateralRatio.Size()
	n += 1 + l + sovEvents(uint64(l))
	return n
}

func (m *EventVaultFunded) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Amount.Size()
	n += 1 + l + sovEvents(uint64(l))
	l = len(m.Source)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = m.NewVaultBalance.Size()
	n += 1 + l + sovEvents(uint64(l))
	return n
}

func (m *EventLedgerRecordExecuted) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovEvents(uint64(l))
	l = len(m.BurnedFrom)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.MintedTo)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.Burner)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.Minter)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.Burned != nil {
		l = m.Burned.Size()
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.Minted != nil {
		l = m.Minted.Size()
		n += 1 + l + sovEvents(uint64(l))
	}
	l = m.Spread.Size()
	n += 1 + l + sovEvents(uint64(l))
	if m.RemintCreditIssued != nil {
		l = m.RemintCreditIssued.Size()
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.RemintCreditAccrued != nil {
		l = m.RemintCreditAccrued.Size()
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventLedgerRecordCanceled) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovEvents(uint64(l))
	if m.CancelReason != 0 {
		n += 1 + sovEvents(uint64(m.CancelReason))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.To)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = m.CoinsToBurn.Size()
	n += 1 + l + sovEvents(uint64(l))
	l = len(m.DenomToMint)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventMintStatusChange) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventMintStatusChange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventMintStatusChange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousStatus", wireType)
			}
			m.PreviousStatus = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PreviousStatus |= MintStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewStatus", wireType)
			}
			m.NewStatus = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NewStatus |= MintStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CollateralRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventVaultFunded) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventVaultFunded: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventVaultFunded: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewVaultBalance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NewVaultBalance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventLedgerRecordExecuted) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventLedgerRecordExecuted: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventLedgerRecordExecuted: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnedFrom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BurnedFrom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintedTo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintedTo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Burner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Burner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Minter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Minter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Burned", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Burned == nil {
				m.Burned = &CoinPrice{}
			}
			if err := m.Burned.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Minted", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Minted == nil {
				m.Minted = &CoinPrice{}
			}
			if err := m.Minted.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spread", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spread.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemintCreditIssued", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RemintCreditIssued == nil {
				m.RemintCreditIssued = &CoinPrice{}
			}
			if err := m.RemintCreditIssued.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemintCreditAccrued", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RemintCreditAccrued == nil {
				m.RemintCreditAccrued = &CoinPrice{}
			}
			if err := m.RemintCreditAccrued.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventLedgerRecordCanceled) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventLedgerRecordCanceled: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventLedgerRecordCanceled: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CancelReason", wireType)
			}
			m.CancelReason = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CancelReason |= LedgerCanceledRecord_BMCancelReason(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.To = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinsToBurn", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CoinsToBurn.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomToMint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DenomToMint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
