// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/oracle/v2/params.proto

package v2

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	any "github.com/cosmos/gogoproto/types/any"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the oracle module
type Params struct {
	// sources addresses allowed to write prices into oracle module
	// those are to be smartcontract addresses
	Sources []string `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources" yaml:"sources"`
	// Minimum number of price sources required (default: 1)
	MinPriceSources uint32 `protobuf:"varint,2,opt,name=min_price_sources,json=minPriceSources,proto3" json:"min_price_sources,omitempty"`
	// Maximum price staleness in seconds (default: 60s)
	MaxPriceStalenessPeriod time.Duration `protobuf:"bytes,3,opt,name=max_price_staleness_period,json=maxPriceStalenessPeriod,proto3,stdduration" json:"max_price_staleness_period" yaml:"max_price_staleness_period"`
	// TWAP window as a duration (default: 5s)
	TwapWindow time.Duration `protobuf:"bytes,4,opt,name=twap_window,json=twapWindow,proto3,stdduration" json:"twap_window" yaml:"twap_window"`
	// Maximum price deviation in basis points (default: 150 = 1.5%)
	MaxPriceDeviationBps uint64 `protobuf:"varint,5,opt,name=max_price_deviation_bps,json=maxPriceDeviationBps,proto3" json:"max_price_deviation_bps,omitempty"`
	// feed_contracts_params contains the configuration for the price feed contracts
	FeedContractsParams []*any.Any `protobuf:"bytes,6,rep,name=feed_contracts_params,json=feedContractsParams,proto3" json:"feed_contracts_params,omitempty"`
	// price_retention is how long to keep price records (default: 24h)
	PriceRetention time.Duration `protobuf:"bytes,7,opt,name=price_retention,json=priceRetention,proto3,stdduration" json:"price_retention" yaml:"price_retention"`
	// prune_epoch is the epoch identifier that triggers pruning (default: "hour")
	PruneEpoch string `protobuf:"bytes,8,opt,name=prune_epoch,json=pruneEpoch,proto3" json:"prune_epoch" yaml:"prune_epoch"`
	// max_prune_per_epoch is the max records to delete per epoch pruning pass (default: 1000)
	MaxPrunePerEpoch int64 `protobuf:"varint,9,opt,name=max_prune_per_epoch,json=maxPrunePerEpoch,proto3" json:"max_prune_per_epoch,omitempty"`
	// max_future_time_drift is the maximum amount of time a price timestamp
	// may exceed the current block time (default: 1m)
	MaxFutureTimeDrift time.Duration `protobuf:"bytes,10,opt,name=max_future_time_drift,json=maxFutureTimeDrift,proto3,stdduration" json:"max_future_time_drift" yaml:"max_future_time_drift"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_07f4d33c5e074ca9, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetSources() []string {
	if m != nil {
		return m.Sources
	}
	return nil
}

func (m *Params) GetMinPriceSources() uint32 {
	if m != nil {
		return m.MinPriceSources
	}
	return 0
}

func (m *Params) GetMaxPriceStalenessPeriod() time.Duration {
	if m != nil {
		return m.MaxPriceStalenessPeriod
	}
	return 0
}

func (m *Params) GetTwapWindow() time.Duration {
	if m != nil {
		return m.TwapWindow
	}
	return 0
}

func (m *Params) GetMaxPriceDeviationBps() uint64 {
	if m != nil {
		return m.MaxPriceDeviationBps
	}
	return 0
}

func (m *Params) GetFeedContractsParams() []*any.Any {
	if m != nil {
		return m.FeedContractsParams
	}
	return nil
}

func (m *Params) GetPriceRetention() time.Duration {
	if m != nil {
		return m.PriceRetention
	}
	return 0
}

func (m *Params) GetPruneEpoch() string {
	if m != nil {
		return m.PruneEpoch
	}
	return ""
}

func (m *Params) GetMaxPrunePerEpoch() int64 {
	if m != nil {
		return m.MaxPrunePerEpoch
	}
	return 0
}

func (m *Params) GetMaxFutureTimeDrift() time.Duration {
	if m != nil {
		return m.MaxFutureTimeDrift
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "akash.oracle.v2.Params")
}

func init() { proto.RegisterFile("akash/oracle/v2/params.proto", fileDescriptor_07f4d33c5e074ca9) }

var fileDescriptor_07f4d33c5e074ca9 = []byte{
	// 610 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0x41, 0x6b, 0xd4, 0x4e,
	0x18, 0xc6, 0x77, 0xfe, 0xdb, 0x7f, 0x6b, 0x67, 0xb1, 0xd5, 0x74, 0x6b, 0xd3, 0x52, 0x93, 0xb8,
	0x20, 0x04, 0xa1, 0x09, 0xac, 0x14, 0xa1, 0xb7, 0xae, 0xb5, 0x08, 0x1e, 0x5c, 0x52, 0x41, 0xf0,
	0x12, 0xa6, 0xc9, 0x6c, 0x3a, 0x74, 0x33, 0x13, 0x66, 0x26, 0xdb, 0xee, 0xa7, 0xd0, 0xa3, 0x47,
	0xc5, 0xaf, 0xe0, 0x87, 0xe8, 0xb1, 0x78, 0xf2, 0x14, 0xa5, 0xbd, 0x48, 0x8f, 0xfb, 0x09, 0x24,
	0x33, 0x09, 0xbb, 0xb4, 0x6a, 0x6f, 0xfb, 0x3e, 0xbf, 0xf7, 0x7d, 0xf3, 0x3c, 0x2f, 0xc3, 0xc2,
	0x4d, 0x74, 0x8c, 0xc4, 0x91, 0xcf, 0x38, 0x8a, 0x86, 0xd8, 0x1f, 0x75, 0xfd, 0x0c, 0x71, 0x94,
	0x0a, 0x2f, 0xe3, 0x4c, 0x32, 0x63, 0x59, 0x51, 0x4f, 0x53, 0x6f, 0xd4, 0xdd, 0x68, 0x27, 0x2c,
	0x61, 0x8a, 0xf9, 0xe5, 0x2f, 0xdd, 0xb6, 0xb1, 0x1e, 0x31, 0x91, 0x32, 0x11, 0x6a, 0xa0, 0x8b,
	0x1a, 0x25, 0x8c, 0x25, 0x43, 0xec, 0xab, 0xea, 0x30, 0x1f, 0xf8, 0x88, 0x8e, 0x2b, 0x64, 0x5d,
	0x47, 0x71, 0xce, 0x91, 0x24, 0x8c, 0x6a, 0xde, 0xf9, 0xbc, 0x00, 0xe7, 0xfb, 0xca, 0x8d, 0xf1,
	0x1a, 0x2e, 0x08, 0x96, 0xf3, 0x08, 0x0b, 0x13, 0x38, 0x4d, 0x77, 0xb1, 0xb7, 0x7d, 0x55, 0xd8,
	0xb5, 0x34, 0x29, 0xec, 0xa5, 0x31, 0x4a, 0x87, 0x3b, 0x9d, 0x4a, 0xe8, 0x7c, 0xfb, 0xba, 0xd5,
	0xae, 0x5c, 0xec, 0xc6, 0x31, 0xc7, 0x42, 0x1c, 0x48, 0x4e, 0x68, 0x12, 0xd4, 0x23, 0xc6, 0x13,
	0x78, 0x3f, 0x25, 0x34, 0xcc, 0x38, 0x89, 0x70, 0x58, 0xaf, 0xfe, 0xcf, 0x01, 0xee, 0xdd, 0x60,
	0x39, 0x25, 0xb4, 0x5f, 0xea, 0x07, 0x55, 0xef, 0x17, 0x00, 0x37, 0x52, 0x74, 0x5a, 0x37, 0x4b,
	0x34, 0xc4, 0x14, 0x0b, 0x11, 0x66, 0x98, 0x13, 0x16, 0x9b, 0x4d, 0x07, 0xb8, 0xad, 0xee, 0xba,
	0xa7, 0xd3, 0x78, 0x75, 0x1a, 0x6f, 0xaf, 0x4a, 0xd3, 0x7b, 0x75, 0x56, 0xd8, 0x8d, 0xab, 0xc2,
	0xfe, 0xc7, 0x92, 0x49, 0x61, 0x3f, 0xd2, 0x11, 0xfe, 0xde, 0xd3, 0xf9, 0xf8, 0xc3, 0x06, 0xc1,
	0x5a, 0x8a, 0x4e, 0xb5, 0xbb, 0x1a, 0xf7, 0x15, 0x35, 0x08, 0x6c, 0xc9, 0x13, 0x94, 0x85, 0x27,
	0x84, 0xc6, 0xec, 0xc4, 0x9c, 0xbb, 0xcd, 0xd5, 0x56, 0xe5, 0x6a, 0x76, 0x6a, 0x52, 0xd8, 0x86,
	0xb6, 0x31, 0x23, 0xea, 0xef, 0xc2, 0x52, 0x79, 0xab, 0x04, 0x63, 0x1b, 0xae, 0x4d, 0x6d, 0xc6,
	0x78, 0x44, 0xd4, 0xc6, 0xf0, 0x30, 0x13, 0xe6, 0xff, 0x0e, 0x70, 0xe7, 0x82, 0x76, 0x6d, 0x72,
	0xaf, 0x86, 0xbd, 0x4c, 0x18, 0x2f, 0xe1, 0xea, 0x00, 0xe3, 0x38, 0x8c, 0x18, 0x95, 0x1c, 0x45,
	0x52, 0x84, 0xfa, 0xad, 0x99, 0xf3, 0x4e, 0xd3, 0x6d, 0x75, 0xdb, 0x37, 0xbc, 0xee, 0xd2, 0x71,
	0xb0, 0x52, 0x8e, 0x3c, 0xaf, 0x27, 0xaa, 0xe7, 0x30, 0x86, 0xcb, 0xfa, 0xe3, 0x1c, 0x4b, 0x4c,
	0xcb, 0xfd, 0xe6, 0xc2, 0x6d, 0x79, 0xb7, 0xab, 0xbc, 0xd7, 0x27, 0x27, 0x85, 0xfd, 0x40, 0x67,
	0xbe, 0x06, 0x74, 0xee, 0x25, 0xa5, 0x06, 0xb5, 0x68, 0xec, 0xc3, 0x56, 0xc6, 0x73, 0x8a, 0x43,
	0x9c, 0xb1, 0xe8, 0xc8, 0xbc, 0xe3, 0x00, 0x77, 0xb1, 0xf7, 0xb8, 0xbc, 0xe3, 0x8c, 0x3c, 0xbd,
	0xe3, 0x8c, 0xd8, 0x09, 0xa0, 0xaa, 0x5e, 0x94, 0x85, 0xb1, 0x05, 0x57, 0xf4, 0x0d, 0x4b, 0x9e,
	0x61, 0x5e, 0xed, 0x5b, 0x74, 0x80, 0xdb, 0x0c, 0xee, 0xa9, 0xfb, 0xe5, 0x14, 0xf7, 0x31, 0xd7,
	0xed, 0xef, 0x01, 0x5c, 0x2d, 0xfb, 0x07, 0xb9, 0xcc, 0x39, 0x0e, 0x25, 0x49, 0x71, 0x18, 0x73,
	0x32, 0x90, 0x26, 0xbc, 0x2d, 0xf8, 0x6e, 0x15, 0xfc, 0xcf, 0xf3, 0x93, 0xc2, 0xde, 0x9c, 0xbe,
	0xbc, 0x1b, 0x58, 0x1f, 0xc1, 0x48, 0xd1, 0xe9, 0xbe, 0x42, 0x6f, 0x48, 0x8a, 0xf7, 0x4a, 0xb0,
	0x33, 0xf7, 0xeb, 0x93, 0x0d, 0x7a, 0xcf, 0xce, 0x2e, 0x2c, 0x70, 0x7e, 0x61, 0x81, 0x9f, 0x17,
	0x16, 0xf8, 0x70, 0x69, 0x35, 0xce, 0x2f, 0xad, 0xc6, 0xf7, 0x4b, 0xab, 0xf1, 0xee, 0x61, 0x76,
	0x9c, 0x78, 0xe8, 0x58, 0x7a, 0x31, 0x1e, 0xf9, 0x09, 0xf3, 0x29, 0x8b, 0xf1, 0xf4, 0x6f, 0xe6,
	0x70, 0x5e, 0x19, 0x7d, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x64, 0x6e, 0xef, 0x53, 0x80, 0x04,
	0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Sources) != len(that1.Sources) {
		return false
	}
	for i := range this.Sources {
		if this.Sources[i] != that1.Sources[i] {
			return false
		}
	}
	if this.MinPriceSources != that1.MinPriceSources {
		return false
	}
	if this.MaxPriceStalenessPeriod != that1.MaxPriceStalenessPeriod {
		return false
	}
	if this.TwapWindow != that1.TwapWindow {
		return false
	}
	if this.MaxPriceDeviationBps != that1.MaxPriceDeviationBps {
		return false
	}
	if len(this.FeedContractsParams) != len(that1.FeedContractsParams) {
		return false
	}
	for i := range this.FeedContractsParams {
		if !this.FeedContractsParams[i].Equal(that1.FeedContractsParams[i]) {
			return false
		}
	}
	if this.PriceRetention != that1.PriceRetention {
		return false
	}
	if this.PruneEpoch != that1.PruneEpoch {
		return false
	}
	if this.MaxPrunePerEpoch != that1.MaxPrunePerEpoch {
		return false
	}
	if this.MaxFutureTimeDrift != that1.MaxFutureTimeDrift {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.MaxFutureTimeDrift, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxFutureTimeDrift):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x52
	if m.MaxPrunePerEpoch != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxPrunePerEpoch))
		i--
		dAtA[i] = 0x48
	}
	if len(m.PruneEpoch) > 0 {
		i -= len(m.PruneEpoch)
		copy(dAtA[i:], m.PruneEpoch)
		i = encodeVarintParams(dAtA, i, uint64(len(m.PruneEpoch)))
		i--
		dAtA[i] = 0x42
	}
	n2, err2 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.PriceRetention, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.PriceRetention):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintParams(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x3a
	if len(m.FeedContractsParams) > 0 {
		for iNdEx := len(m.FeedContractsParams) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FeedContractsParams[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.MaxPriceDeviationBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxPriceDeviationBps))
		i--
		dAtA[i] = 0x28
	}
	n3, err3 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.TwapWindow, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.TwapWindow):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintParams(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x22
	n4, err4 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.MaxPriceStalenessPeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxPriceStalenessPeriod):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintParams(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x1a
	if m.MinPriceSources != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinPriceSources))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Sources) > 0 {
		for iNdEx := len(m.Sources) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Sources[iNdEx])
			copy(dAtA[i:], m.Sources[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.Sources[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Sources) > 0 {
		for _, s := range m.Sources {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if m.MinPriceSources != 0 {
		n += 1 + sovParams(uint64(m.MinPriceSources))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxPriceStalenessPeriod)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.TwapWindow)
	n += 1 + l + sovParams(uint64(l))
	if m.MaxPriceDeviationBps != 0 {
		n += 1 + sovParams(uint64(m.MaxPriceDeviationBps))
	}
	if len(m.FeedContractsParams) > 0 {
		for _, e := range m.FeedContractsParams {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.PriceRetention)
	n += 1 + l + sovParams(uint64(l))
	l = len(m.PruneEpoch)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.MaxPrunePerEpoch != 0 {
		n += 1 + sovParams(uint64(m.MaxPrunePerEpoch))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxFutureTimeDrift)
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sources", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sources = append(m.Sources, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinPriceSources", wireType)
			}
			m.MinPriceSources = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinPriceSources |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPriceStalenessPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.MaxPriceStalenessPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TwapWindow", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.TwapWindow, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPriceDeviationBps", wireType)
			}
			m.MaxPriceDeviationBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPriceDeviationBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeedContractsParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeedContractsParams = append(m.FeedContractsParams, &any.Any{})
			if err := m.FeedContractsParams[len(m.FeedContractsParams)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceRetention", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.PriceRetention, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PruneEpoch", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PruneEpoch = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPrunePerEpoch", wireType)
			}
			m.MaxPrunePerEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPrunePerEpoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxFutureTimeDrift", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.MaxFutureTimeDrift, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
