// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/provider/v1beta4/params.proto

package v1beta4

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ProviderMaintenanceParams defines maintenance window parameters.
type ProviderMaintenanceParams struct {
	// maintenance_max_duration is the maximum allowed value of
	// (expected_ends_at - starts_at) when opening a maintenance window.
	MaintenanceMaxDuration time.Duration `protobuf:"bytes,1,opt,name=maintenance_max_duration,json=maintenanceMaxDuration,proto3,stdduration" json:"maintenance_max_duration" yaml:"maintenance_max_duration"`
	// maintenance_max_lookahead is the maximum allowed value of
	// (starts_at - block_time) when opening a maintenance window. A value of
	// zero means windows may only start at or before the current block time.
	MaintenanceMaxLookahead time.Duration `protobuf:"bytes,2,opt,name=maintenance_max_lookahead,json=maintenanceMaxLookahead,proto3,stdduration" json:"maintenance_max_lookahead" yaml:"maintenance_max_lookahead"`
}

func (m *ProviderMaintenanceParams) Reset()         { *m = ProviderMaintenanceParams{} }
func (m *ProviderMaintenanceParams) String() string { return proto.CompactTextString(m) }
func (*ProviderMaintenanceParams) ProtoMessage()    {}
func (*ProviderMaintenanceParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec10de0797c14a98, []int{0}
}
func (m *ProviderMaintenanceParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProviderMaintenanceParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProviderMaintenanceParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProviderMaintenanceParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderMaintenanceParams.Merge(m, src)
}
func (m *ProviderMaintenanceParams) XXX_Size() int {
	return m.Size()
}
func (m *ProviderMaintenanceParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderMaintenanceParams.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderMaintenanceParams proto.InternalMessageInfo

func (m *ProviderMaintenanceParams) GetMaintenanceMaxDuration() time.Duration {
	if m != nil {
		return m.MaintenanceMaxDuration
	}
	return 0
}

func (m *ProviderMaintenanceParams) GetMaintenanceMaxLookahead() time.Duration {
	if m != nil {
		return m.MaintenanceMaxLookahead
	}
	return 0
}

func init() {
	proto.RegisterType((*ProviderMaintenanceParams)(nil), "akash.provider.v1beta4.ProviderMaintenanceParams")
}

func init() {
	proto.RegisterFile("akash/provider/v1beta4/params.proto", fileDescriptor_ec10de0797c14a98)
}

var fileDescriptor_ec10de0797c14a98 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4e, 0xcc, 0x4e, 0x2c,
	0xce, 0xd0, 0x2f, 0x28, 0xca, 0x2f, 0xcb, 0x4c, 0x49, 0x2d, 0xd2, 0x2f, 0x33, 0x4c, 0x4a, 0x2d,
	0x49, 0x34, 0xd1, 0x2f, 0x48, 0x2c, 0x4a, 0xcc, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x12, 0x03, 0x2b, 0xd2, 0x83, 0x29, 0xd2, 0x83, 0x2a, 0x92, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07,
	0x2b, 0xd1, 0x07, 0xb1, 0x20, 0xaa, 0xa5, 0xe4, 0xd2, 0xf3, 0xf3, 0xd3, 0x73, 0x52, 0xf5, 0xc1,
	0xbc, 0xa4, 0xd2, 0x34, 0xfd, 0x94, 0xd2, 0xa2, 0xc4, 0x92, 0xcc, 0xfc, 0x3c, 0x88, 0xbc, 0xd2,
	0x5d, 0x26, 0x2e, 0xc9, 0x00, 0xa8, 0x51, 0xbe, 0x89, 0x99, 0x79, 0x25, 0xa9, 0x79, 0x89, 0x79,
	0xc9, 0xa9, 0x01, 0x60, 0x1b, 0x85, 0xe6, 0x30, 0x72, 0x49, 0xe4, 0x22, 0x44, 0xe3, 0x73, 0x13,
	0x2b, 0xe2, 0x61, 0x06, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x49, 0xea, 0x41, 0x6c, 0xd0,
	0x83, 0xd9, 0xa0, 0xe7, 0x02, 0x55, 0xe0, 0xe4, 0x7e, 0xe2, 0x9e, 0x3c, 0xc3, 0xab, 0x7b, 0xf2,
	0x38, 0x8d, 0xf8, 0x74, 0x4f, 0x5e, 0xbe, 0x32, 0x31, 0x37, 0xc7, 0x4a, 0x09, 0x97, 0x0a, 0xa5,
	0x19, 0xf7, 0xe5, 0x19, 0x83, 0xc4, 0x90, 0xa4, 0x7d, 0x13, 0x2b, 0x60, 0x16, 0x08, 0x2d, 0x60,
	0xe4, 0x92, 0x44, 0xd7, 0x99, 0x93, 0x9f, 0x9f, 0x9d, 0x98, 0x91, 0x9a, 0x98, 0x22, 0xc1, 0x44,
	0xc8, 0x7d, 0x9e, 0x50, 0xf7, 0xe1, 0x36, 0xe3, 0xd3, 0x3d, 0x79, 0x05, 0xec, 0x0e, 0x84, 0x2b,
	0x81, 0xb8, 0x50, 0x1c, 0xd5, 0x85, 0x3e, 0x30, 0x59, 0x27, 0xbb, 0x13, 0x8f, 0xe4, 0x18, 0x2f,
	0x3c, 0x92, 0x63, 0x7c, 0xf0, 0x48, 0x8e, 0x71, 0xc2, 0x63, 0x39, 0x86, 0x0b, 0x8f, 0xe5, 0x18,
	0x6e, 0x3c, 0x96, 0x63, 0x88, 0x52, 0x29, 0xc8, 0x4e, 0xd7, 0x4b, 0xcc, 0x2e, 0xd1, 0x4b, 0x49,
	0x2d, 0xd3, 0x4f, 0xcf, 0xd7, 0xcf, 0xcb, 0x4f, 0x49, 0xc5, 0x88, 0xfa, 0x24, 0x36, 0xb0, 0xb3,
	0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x07, 0xd6, 0xc7, 0x9d, 0x1b, 0x02, 0x00, 0x00,
}

func (m *ProviderMaintenanceParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProviderMaintenanceParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProviderMaintenanceParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.MaintenanceMaxLookahead, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaintenanceMaxLookahead):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x12
	n2, err2 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.MaintenanceMaxDuration, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaintenanceMaxDuration):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintParams(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ProviderMaintenanceParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaintenanceMaxDuration)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaintenanceMaxLookahead)
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ProviderMaintenanceParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProviderMaintenanceParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProviderMaintenanceParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaintenanceMaxDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.MaintenanceMaxDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaintenanceMaxLookahead", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.MaintenanceMaxLookahead, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
