// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/inventory/v1/resources.proto

package v1

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// NodeResources reports node inventory details
type NodeResources struct {
	CPU              CPU          `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu" yaml:"cpu"`
	Memory           Memory       `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory" yaml:"memory"`
	GPU              GPU          `protobuf:"bytes,3,opt,name=gpu,proto3,castrepeated=GPUs" json:"gpu" yaml:"gpu"`
	EphemeralStorage ResourcePair `protobuf:"bytes,4,opt,name=ephemeral_storage,json=ephemeralStorage,proto3" json:"ephemeral_storage" yaml:"ephemeral_storage"`
	VolumesAttached  ResourcePair `protobuf:"bytes,5,opt,name=volumes_attached,json=volumesAttached,proto3" json:"volumes_attached" yaml:"volumes_attached"`
	VolumesMounted   ResourcePair `protobuf:"bytes,6,opt,name=volumes_mounted,json=volumesMounted,proto3" json:"volumes_mounted" yaml:"volumes_mounted"`
	// GPUInterconnect reports node GPU-interconnect HCA capacity.
	// Capacity/Allocatable/Allocated are populated by the inventory
	// operator from k8s allocatable for whichever
	// rdma/rdma_shared_device_* extended resource the cluster's device
	// plugin publishes (the `rdma/*` prefix is the device plugin's
	// naming convention; see NodeCapabilities.interconnect_resource_name).
	GPUInterconnect ResourcePair `protobuf:"bytes,7,opt,name=gpu_interconnect,json=gpuInterconnect,proto3" json:"gpu_interconnect" yaml:"gpu_interconnect"`
}

func (m *NodeResources) Reset()         { *m = NodeResources{} }
func (m *NodeResources) String() string { return proto.CompactTextString(m) }
func (*NodeResources) ProtoMessage()    {}
func (*NodeResources) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20a722bd8ee01b5, []int{0}
}
func (m *NodeResources) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeResources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NodeResources.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NodeResources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeResources.Merge(m, src)
}
func (m *NodeResources) XXX_Size() int {
	return m.Size()
}
func (m *NodeResources) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeResources.DiscardUnknown(m)
}

var xxx_messageInfo_NodeResources proto.InternalMessageInfo

func (m *NodeResources) GetCPU() CPU {
	if m != nil {
		return m.CPU
	}
	return CPU{}
}

func (m *NodeResources) GetMemory() Memory {
	if m != nil {
		return m.Memory
	}
	return Memory{}
}

func (m *NodeResources) GetGPU() GPU {
	if m != nil {
		return m.GPU
	}
	return GPU{}
}

func (m *NodeResources) GetEphemeralStorage() ResourcePair {
	if m != nil {
		return m.EphemeralStorage
	}
	return ResourcePair{}
}

func (m *NodeResources) GetVolumesAttached() ResourcePair {
	if m != nil {
		return m.VolumesAttached
	}
	return ResourcePair{}
}

func (m *NodeResources) GetVolumesMounted() ResourcePair {
	if m != nil {
		return m.VolumesMounted
	}
	return ResourcePair{}
}

func (m *NodeResources) GetGPUInterconnect() ResourcePair {
	if m != nil {
		return m.GPUInterconnect
	}
	return ResourcePair{}
}

func init() {
	proto.RegisterType((*NodeResources)(nil), "akash.inventory.v1.NodeResources")
}

func init() {
	proto.RegisterFile("akash/inventory/v1/resources.proto", fileDescriptor_f20a722bd8ee01b5)
}

var fileDescriptor_f20a722bd8ee01b5 = []byte{
	// 514 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xc1, 0x8a, 0xd3, 0x40,
	0x18, 0xc7, 0x1b, 0xbb, 0x56, 0x88, 0xec, 0xb6, 0x06, 0x71, 0x43, 0x95, 0x4c, 0x19, 0x10, 0xd6,
	0x4b, 0xc2, 0x2a, 0x5e, 0xbc, 0x99, 0xa2, 0x65, 0x91, 0x95, 0x90, 0x25, 0x1e, 0x04, 0x29, 0x63,
	0x3a, 0x4c, 0x4b, 0x9b, 0xcc, 0x90, 0x64, 0x02, 0xfb, 0x12, 0x22, 0x78, 0xf1, 0x19, 0x7c, 0x92,
	0x3d, 0xee, 0xd1, 0xd3, 0x28, 0xed, 0x45, 0x72, 0xcc, 0x13, 0x48, 0x32, 0xc9, 0xda, 0xa6, 0x75,
	0xd9, 0xbd, 0x25, 0xf3, 0xff, 0xbe, 0xdf, 0xf7, 0x9b, 0x0f, 0x46, 0x85, 0x68, 0x8e, 0xe2, 0xa9,
	0x35, 0x0b, 0x53, 0x1c, 0x26, 0x34, 0x3a, 0xb7, 0xd2, 0x63, 0x2b, 0xc2, 0x31, 0xe5, 0x91, 0x8f,
	0x63, 0x93, 0x45, 0x34, 0xa1, 0x9a, 0x56, 0xd6, 0x98, 0x57, 0x35, 0x66, 0x7a, 0xdc, 0x7f, 0x48,
	0x28, 0xa1, 0x65, 0x6c, 0x15, 0x5f, 0xb2, 0xb2, 0xff, 0x64, 0x07, 0xcd, 0x67, 0xfc, 0x9a, 0x94,
	0x5c, 0xa5, 0x60, 0x47, 0x1a, 0xe0, 0xa0, 0x98, 0x27, 0x0b, 0x9e, 0x5e, 0xa3, 0xca, 0xd0, 0x2c,
	0x92, 0x65, 0xf0, 0x4f, 0x47, 0xdd, 0x7f, 0x4f, 0x27, 0xd8, 0xad, 0x6f, 0xa1, 0xbd, 0x53, 0xdb,
	0x3e, 0xe3, 0xba, 0x32, 0x50, 0x8e, 0xee, 0x3f, 0x3f, 0x34, 0xb7, 0x6f, 0x63, 0x0e, 0x1d, 0xcf,
	0x1e, 0x5c, 0x08, 0xd0, 0x5a, 0x0a, 0xd0, 0x1e, 0x3a, 0x5e, 0x26, 0x40, 0xd1, 0x92, 0x0b, 0xa0,
	0x9e, 0xa3, 0x60, 0xf1, 0x0a, 0xfa, 0x8c, 0x43, 0xb7, 0x38, 0xd2, 0x3e, 0xa9, 0x1d, 0x69, 0xa5,
	0xdf, 0x29, 0x79, 0xfd, 0x5d, 0xbc, 0xd3, 0xb2, 0xc2, 0x7e, 0x56, 0x21, 0x3b, 0xf2, 0x3f, 0x13,
	0xa0, 0xea, 0xcd, 0x05, 0xd8, 0x97, 0x60, 0xf9, 0x0f, 0xdd, 0x2a, 0xd0, 0xce, 0xd4, 0x36, 0x61,
	0x5c, 0x6f, 0xff, 0xdf, 0x75, 0xe4, 0x78, 0xf6, 0x51, 0xed, 0x3a, 0x92, 0xae, 0x64, 0xdd, 0x95,
	0x30, 0x0e, 0x7f, 0xfc, 0x02, 0x7b, 0x23, 0xc7, 0x8b, 0xdd, 0x22, 0xd2, 0xbe, 0x2b, 0xea, 0x03,
	0xcc, 0xa6, 0x38, 0xc0, 0x11, 0x5a, 0x8c, 0xe3, 0x84, 0x46, 0x88, 0x60, 0x7d, 0xaf, 0x9c, 0x31,
	0xd8, 0x35, 0xa3, 0xde, 0x9d, 0x83, 0x66, 0x91, 0x7d, 0x52, 0x0d, 0xeb, 0xbd, 0xa9, 0x11, 0x67,
	0x92, 0x90, 0x09, 0xb0, 0x8d, 0xcd, 0x05, 0xd0, 0xa5, 0xc7, 0x56, 0x04, 0xdd, 0x1e, 0x6e, 0x20,
	0xb4, 0x6f, 0x8a, 0xda, 0x4b, 0xe9, 0x82, 0x07, 0x38, 0x1e, 0xa3, 0x24, 0x41, 0xfe, 0x14, 0x4f,
	0xf4, 0xbb, 0x37, 0x34, 0x7b, 0x5b, 0x99, 0x75, 0x3f, 0x48, 0xc2, 0xeb, 0x0a, 0x90, 0x09, 0xb0,
	0x05, 0xcd, 0x05, 0x38, 0x94, 0x5e, 0xcd, 0x04, 0xba, 0xdd, 0x74, 0xb3, 0x5f, 0xfb, 0xa2, 0xa8,
	0xf5, 0xd9, 0x38, 0xa0, 0x3c, 0x4c, 0xf0, 0x44, 0xef, 0xdc, 0x50, 0x6a, 0x58, 0x49, 0x1d, 0x54,
	0x52, 0xa7, 0xb2, 0x3f, 0x13, 0xa0, 0x89, 0xcc, 0x05, 0x78, 0xb4, 0xa9, 0x54, 0x05, 0xd0, 0x3d,
	0x48, 0x37, 0x9a, 0xcb, 0x35, 0x11, 0xc6, 0xc7, 0xb3, 0x30, 0xc1, 0x91, 0x4f, 0xc3, 0x10, 0xfb,
	0x89, 0x7e, 0xef, 0xb6, 0x6b, 0x1a, 0x39, 0xde, 0xc9, 0x1a, 0xa0, 0x58, 0x53, 0x13, 0xfa, 0x6f,
	0x4d, 0xcd, 0x04, 0xba, 0x5d, 0xc2, 0xf8, 0x7a, 0xbf, 0xfd, 0xf2, 0x62, 0x69, 0x28, 0x97, 0x4b,
	0x43, 0xf9, 0xbd, 0x34, 0x94, 0xaf, 0x2b, 0xa3, 0x75, 0xb9, 0x32, 0x5a, 0x3f, 0x57, 0x46, 0xeb,
	0xe3, 0x63, 0x36, 0x27, 0x26, 0x9a, 0x27, 0xe6, 0x04, 0xa7, 0x16, 0xa1, 0x1b, 0x8f, 0xf6, 0x73,
	0xa7, 0x7c, 0xa8, 0x2f, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x10, 0xed, 0x3d, 0xce, 0x7c, 0x04,
	0x00, 0x00,
}

func (m *NodeResources) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeResources) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeResources) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.GPUInterconnect.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintResources(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.VolumesMounted.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintResources(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.VolumesAttached.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintResources(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.EphemeralStorage.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintResources(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.GPU.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintResources(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Memory.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintResources(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.CPU.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintResources(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintResources(dAtA []byte, offset int, v uint64) int {
	offset -= sovResources(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NodeResources) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CPU.Size()
	n += 1 + l + sovResources(uint64(l))
	l = m.Memory.Size()
	n += 1 + l + sovResources(uint64(l))
	l = m.GPU.Size()
	n += 1 + l + sovResources(uint64(l))
	l = m.EphemeralStorage.Size()
	n += 1 + l + sovResources(uint64(l))
	l = m.VolumesAttached.Size()
	n += 1 + l + sovResources(uint64(l))
	l = m.VolumesMounted.Size()
	n += 1 + l + sovResources(uint64(l))
	l = m.GPUInterconnect.Size()
	n += 1 + l + sovResources(uint64(l))
	return n
}

func sovResources(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozResources(x uint64) (n int) {
	return sovResources(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NodeResources) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowResources
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeResources: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeResources: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CPU", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResources
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthResources
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthResources
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CPU.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memory", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResources
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthResources
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthResources
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Memory.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GPU", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResources
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthResources
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthResources
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GPU.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EphemeralStorage", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResources
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthResources
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthResources
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EphemeralStorage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VolumesAttached", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResources
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthResources
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthResources
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VolumesAttached.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VolumesMounted", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResources
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthResources
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthResources
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VolumesMounted.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GPUInterconnect", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResources
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthResources
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthResources
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GPUInterconnect.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipResources(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthResources
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipResources(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowResources
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowResources
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowResources
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthResources
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupResources
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthResources
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthResources        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowResources          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupResources = fmt.Errorf("proto: unexpected end of group")
)
