// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/inventory/v1/snapshot.proto

package v1

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SnapshotPayload is the deterministic payload signed by a provider.
type SnapshotPayload struct {
	// schema_version identifies the payload schema used by snapshot_payload.
	SchemaVersion uint32 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version" yaml:"schema_version"`
	// provider is the provider account address in bech32 form.
	Provider string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider" yaml:"provider"`
	// chain_id binds the snapshot to the chain the provider is operating on.
	ChainID string `protobuf:"bytes,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id" yaml:"chain_id"`
	// nonce is the optional challenge supplied by the caller.
	Nonce []byte `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce" yaml:"nonce"`
	// timestamp is the provider-local snapshot generation time.
	Timestamp time.Time `protobuf:"bytes,5,opt,name=timestamp,proto3,stdtime" json:"timestamp" yaml:"timestamp"`
	// cluster is the current cluster inventory view.
	Cluster Cluster `protobuf:"bytes,6,opt,name=cluster,proto3" json:"cluster" yaml:"cluster"`
	// resource_summary is the chain-facing summary derived from the full snapshot.
	ResourceSummary SnapshotResourceSummary `protobuf:"bytes,7,opt,name=resource_summary,json=resourceSummary,proto3" json:"resource_summary" yaml:"resource_summary"`
	// evidence_sections carries named collector payloads for auditor evidence.
	EvidenceSections []SnapshotEvidenceSection `protobuf:"bytes,8,rep,name=evidence_sections,json=evidenceSections,proto3" json:"evidence_sections" yaml:"evidence_sections"`
}

func (m *SnapshotPayload) Reset()         { *m = SnapshotPayload{} }
func (m *SnapshotPayload) String() string { return proto.CompactTextString(m) }
func (*SnapshotPayload) ProtoMessage()    {}
func (*SnapshotPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad89c697cb83f0ea, []int{0}
}
func (m *SnapshotPayload) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SnapshotPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SnapshotPayload.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SnapshotPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotPayload.Merge(m, src)
}
func (m *SnapshotPayload) XXX_Size() int {
	return m.Size()
}
func (m *SnapshotPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotPayload.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotPayload proto.InternalMessageInfo

func (m *SnapshotPayload) GetSchemaVersion() uint32 {
	if m != nil {
		return m.SchemaVersion
	}
	return 0
}

func (m *SnapshotPayload) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *SnapshotPayload) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *SnapshotPayload) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *SnapshotPayload) GetTimestamp() time.Time {
	if m != nil {
		return m.Timestamp
	}
	return time.Time{}
}

func (m *SnapshotPayload) GetCluster() Cluster {
	if m != nil {
		return m.Cluster
	}
	return Cluster{}
}

func (m *SnapshotPayload) GetResourceSummary() SnapshotResourceSummary {
	if m != nil {
		return m.ResourceSummary
	}
	return SnapshotResourceSummary{}
}

func (m *SnapshotPayload) GetEvidenceSections() []SnapshotEvidenceSection {
	if m != nil {
		return m.EvidenceSections
	}
	return nil
}

// SoftwareIdentity carries release artifact identity and signature metadata.
// Providers report these fields; auditors verify them off-chain against the
// published Akash release key.
type SoftwareIdentity struct {
	// version is the provider or inventory software version string.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version" yaml:"version"`
	// artifact_ref identifies the release artifact whose digest/signature is reported.
	ArtifactRef string `protobuf:"bytes,2,opt,name=artifact_ref,json=artifactRef,proto3" json:"artifact_ref" yaml:"artifact_ref"`
	// digest_algorithm identifies the digest algorithm, e.g. sha3-256.
	DigestAlgorithm string `protobuf:"bytes,3,opt,name=digest_algorithm,json=digestAlgorithm,proto3" json:"digest_algorithm" yaml:"digest_algorithm"`
	// digest is the release artifact digest bytes.
	Digest []byte `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest" yaml:"digest"`
	// signature_type identifies the signature format, e.g. cosign.
	SignatureType string `protobuf:"bytes,5,opt,name=signature_type,json=signatureType,proto3" json:"signature_type" yaml:"signature_type"`
	// signature is the detached signature bytes when carried inline.
	Signature []byte `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature" yaml:"signature"`
	// signature_ref identifies an external signature or bundle.
	SignatureRef string `protobuf:"bytes,7,opt,name=signature_ref,json=signatureRef,proto3" json:"signature_ref" yaml:"signature_ref"`
	// public_key_ref identifies the published release public key.
	PublicKeyRef string `protobuf:"bytes,8,opt,name=public_key_ref,json=publicKeyRef,proto3" json:"public_key_ref" yaml:"public_key_ref"`
}

func (m *SoftwareIdentity) Reset()         { *m = SoftwareIdentity{} }
func (m *SoftwareIdentity) String() string { return proto.CompactTextString(m) }
func (*SoftwareIdentity) ProtoMessage()    {}
func (*SoftwareIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad89c697cb83f0ea, []int{1}
}
func (m *SoftwareIdentity) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SoftwareIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SoftwareIdentity.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SoftwareIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoftwareIdentity.Merge(m, src)
}
func (m *SoftwareIdentity) XXX_Size() int {
	return m.Size()
}
func (m *SoftwareIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_SoftwareIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_SoftwareIdentity proto.InternalMessageInfo

func (m *SoftwareIdentity) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SoftwareIdentity) GetArtifactRef() string {
	if m != nil {
		return m.ArtifactRef
	}
	return ""
}

func (m *SoftwareIdentity) GetDigestAlgorithm() string {
	if m != nil {
		return m.DigestAlgorithm
	}
	return ""
}

func (m *SoftwareIdentity) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func (m *SoftwareIdentity) GetSignatureType() string {
	if m != nil {
		return m.SignatureType
	}
	return ""
}

func (m *SoftwareIdentity) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SoftwareIdentity) GetSignatureRef() string {
	if m != nil {
		return m.SignatureRef
	}
	return ""
}

func (m *SoftwareIdentity) GetPublicKeyRef() string {
	if m != nil {
		return m.PublicKeyRef
	}
	return ""
}

// SnapshotResourceSummary captures the snapshot fields posted on-chain.
type SnapshotResourceSummary struct {
	TotalGPUs      uint32 `protobuf:"varint,1,opt,name=total_gpus,json=totalGpus,proto3" json:"total_gpus" yaml:"total_gpus"`
	TotalVCPUs     uint32 `protobuf:"varint,2,opt,name=total_vcpus,json=totalVcpus,proto3" json:"total_vcpus" yaml:"total_vcpus"`
	TotalMemoryMB  uint64 `protobuf:"varint,3,opt,name=total_memory_mb,json=totalMemoryMb,proto3" json:"total_memory_mb" yaml:"total_memory_mb"`
	TotalStorageMB uint64 `protobuf:"varint,4,opt,name=total_storage_mb,json=totalStorageMb,proto3" json:"total_storage_mb" yaml:"total_storage_mb"`
	ActiveLeases   uint32 `protobuf:"varint,5,opt,name=active_leases,json=activeLeases,proto3" json:"active_leases" yaml:"active_leases"`
	// software_version is the provider software version string kept for compatibility.
	SoftwareVersion string `protobuf:"bytes,6,opt,name=software_version,json=softwareVersion,proto3" json:"software_version" yaml:"software_version"`
	// software_signature is the provider software signature kept for compatibility.
	SoftwareSignature []byte `protobuf:"bytes,7,opt,name=software_signature,json=softwareSignature,proto3" json:"software_signature" yaml:"software_signature"`
	// software_identity carries structured release artifact metadata.
	SoftwareIdentity *SoftwareIdentity `protobuf:"bytes,8,opt,name=software_identity,json=softwareIdentity,proto3" json:"software_identity,omitempty" yaml:"software_identity,omitempty"`
}

func (m *SnapshotResourceSummary) Reset()         { *m = SnapshotResourceSummary{} }
func (m *SnapshotResourceSummary) String() string { return proto.CompactTextString(m) }
func (*SnapshotResourceSummary) ProtoMessage()    {}
func (*SnapshotResourceSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad89c697cb83f0ea, []int{2}
}
func (m *SnapshotResourceSummary) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SnapshotResourceSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SnapshotResourceSummary.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SnapshotResourceSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotResourceSummary.Merge(m, src)
}
func (m *SnapshotResourceSummary) XXX_Size() int {
	return m.Size()
}
func (m *SnapshotResourceSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotResourceSummary.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotResourceSummary proto.InternalMessageInfo

func (m *SnapshotResourceSummary) GetTotalGPUs() uint32 {
	if m != nil {
		return m.TotalGPUs
	}
	return 0
}

func (m *SnapshotResourceSummary) GetTotalVCPUs() uint32 {
	if m != nil {
		return m.TotalVCPUs
	}
	return 0
}

func (m *SnapshotResourceSummary) GetTotalMemoryMB() uint64 {
	if m != nil {
		return m.TotalMemoryMB
	}
	return 0
}

func (m *SnapshotResourceSummary) GetTotalStorageMB() uint64 {
	if m != nil {
		return m.TotalStorageMB
	}
	return 0
}

func (m *SnapshotResourceSummary) GetActiveLeases() uint32 {
	if m != nil {
		return m.ActiveLeases
	}
	return 0
}

func (m *SnapshotResourceSummary) GetSoftwareVersion() string {
	if m != nil {
		return m.SoftwareVersion
	}
	return ""
}

func (m *SnapshotResourceSummary) GetSoftwareSignature() []byte {
	if m != nil {
		return m.SoftwareSignature
	}
	return nil
}

func (m *SnapshotResourceSummary) GetSoftwareIdentity() *SoftwareIdentity {
	if m != nil {
		return m.SoftwareIdentity
	}
	return nil
}

// SnapshotEvidenceSection carries an opaque payload from one collector.
type SnapshotEvidenceSection struct {
	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name" yaml:"name"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload" yaml:"payload"`
}

func (m *SnapshotEvidenceSection) Reset()         { *m = SnapshotEvidenceSection{} }
func (m *SnapshotEvidenceSection) String() string { return proto.CompactTextString(m) }
func (*SnapshotEvidenceSection) ProtoMessage()    {}
func (*SnapshotEvidenceSection) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad89c697cb83f0ea, []int{3}
}
func (m *SnapshotEvidenceSection) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SnapshotEvidenceSection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SnapshotEvidenceSection.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SnapshotEvidenceSection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotEvidenceSection.Merge(m, src)
}
func (m *SnapshotEvidenceSection) XXX_Size() int {
	return m.Size()
}
func (m *SnapshotEvidenceSection) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotEvidenceSection.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotEvidenceSection proto.InternalMessageInfo

func (m *SnapshotEvidenceSection) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SnapshotEvidenceSection) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// GetInventorySnapshotRequest is the request type for GetInventorySnapshot.
type GetInventorySnapshotRequest struct {
	// nonce is an optional 32-byte challenge bound into the signed payload.
	Nonce []byte `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (m *GetInventorySnapshotRequest) Reset()         { *m = GetInventorySnapshotRequest{} }
func (m *GetInventorySnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*GetInventorySnapshotRequest) ProtoMessage()    {}
func (*GetInventorySnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad89c697cb83f0ea, []int{4}
}
func (m *GetInventorySnapshotRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetInventorySnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetInventorySnapshotRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetInventorySnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInventorySnapshotRequest.Merge(m, src)
}
func (m *GetInventorySnapshotRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetInventorySnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInventorySnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInventorySnapshotRequest proto.InternalMessageInfo

func (m *GetInventorySnapshotRequest) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

// GetInventorySnapshotResponse is the response type for GetInventorySnapshot.
type GetInventorySnapshotResponse struct {
	// snapshot_payload is the opaque inventory snapshot payload.
	SnapshotPayload []byte `protobuf:"bytes,1,opt,name=snapshot_payload,json=snapshotPayload,proto3" json:"snapshot_payload,omitempty"`
	// signature is the provider signature over snapshot_payload.
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// provider is the provider account address in bech32 form.
	Provider string `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
}

func (m *GetInventorySnapshotResponse) Reset()         { *m = GetInventorySnapshotResponse{} }
func (m *GetInventorySnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*GetInventorySnapshotResponse) ProtoMessage()    {}
func (*GetInventorySnapshotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad89c697cb83f0ea, []int{5}
}
func (m *GetInventorySnapshotResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetInventorySnapshotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetInventorySnapshotResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetInventorySnapshotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInventorySnapshotResponse.Merge(m, src)
}
func (m *GetInventorySnapshotResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetInventorySnapshotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInventorySnapshotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInventorySnapshotResponse proto.InternalMessageInfo

func (m *GetInventorySnapshotResponse) GetSnapshotPayload() []byte {
	if m != nil {
		return m.SnapshotPayload
	}
	return nil
}

func (m *GetInventorySnapshotResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *GetInventorySnapshotResponse) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

// GetCommittedInventorySnapshotRequest is the request type for
// GetCommittedInventorySnapshot.
type GetCommittedInventorySnapshotRequest struct {
	// snapshot_hash optionally selects a committed snapshot by SHA-256 hash. When
	// omitted, the latest committed snapshot is returned.
	SnapshotHash []byte `protobuf:"bytes,1,opt,name=snapshot_hash,json=snapshotHash,proto3" json:"snapshot_hash,omitempty"`
}

func (m *GetCommittedInventorySnapshotRequest) Reset()         { *m = GetCommittedInventorySnapshotRequest{} }
func (m *GetCommittedInventorySnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*GetCommittedInventorySnapshotRequest) ProtoMessage()    {}
func (*GetCommittedInventorySnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad89c697cb83f0ea, []int{6}
}
func (m *GetCommittedInventorySnapshotRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetCommittedInventorySnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetCommittedInventorySnapshotRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetCommittedInventorySnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommittedInventorySnapshotRequest.Merge(m, src)
}
func (m *GetCommittedInventorySnapshotRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetCommittedInventorySnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommittedInventorySnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommittedInventorySnapshotRequest proto.InternalMessageInfo

func (m *GetCommittedInventorySnapshotRequest) GetSnapshotHash() []byte {
	if m != nil {
		return m.SnapshotHash
	}
	return nil
}

// GetCommittedInventorySnapshotResponse is the response type for
// GetCommittedInventorySnapshot.
type GetCommittedInventorySnapshotResponse struct {
	// snapshot_payload is the exact committed inventory snapshot payload.
	SnapshotPayload []byte `protobuf:"bytes,1,opt,name=snapshot_payload,json=snapshotPayload,proto3" json:"snapshot_payload,omitempty"`
	// signature is the provider signature over snapshot_payload.
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// provider is the provider account address in bech32 form.
	Provider string `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	// snapshot_hash is the SHA-256 hash of snapshot_payload.
	SnapshotHash []byte `protobuf:"bytes,4,opt,name=snapshot_hash,json=snapshotHash,proto3" json:"snapshot_hash,omitempty"`
	// posted_at is when the provider stored this committed snapshot locally.
	PostedAt time.Time `protobuf:"bytes,5,opt,name=posted_at,json=postedAt,proto3,stdtime" json:"posted_at" yaml:"posted_at"`
}

func (m *GetCommittedInventorySnapshotResponse) Reset()         { *m = GetCommittedInventorySnapshotResponse{} }
func (m *GetCommittedInventorySnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*GetCommittedInventorySnapshotResponse) ProtoMessage()    {}
func (*GetCommittedInventorySnapshotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad89c697cb83f0ea, []int{7}
}
func (m *GetCommittedInventorySnapshotResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetCommittedInventorySnapshotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetCommittedInventorySnapshotResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetCommittedInventorySnapshotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommittedInventorySnapshotResponse.Merge(m, src)
}
func (m *GetCommittedInventorySnapshotResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetCommittedInventorySnapshotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommittedInventorySnapshotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommittedInventorySnapshotResponse proto.InternalMessageInfo

func (m *GetCommittedInventorySnapshotResponse) GetSnapshotPayload() []byte {
	if m != nil {
		return m.SnapshotPayload
	}
	return nil
}

func (m *GetCommittedInventorySnapshotResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *GetCommittedInventorySnapshotResponse) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *GetCommittedInventorySnapshotResponse) GetSnapshotHash() []byte {
	if m != nil {
		return m.SnapshotHash
	}
	return nil
}

func (m *GetCommittedInventorySnapshotResponse) GetPostedAt() time.Time {
	if m != nil {
		return m.PostedAt
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*SnapshotPayload)(nil), "akash.inventory.v1.SnapshotPayload")
	proto.RegisterType((*SoftwareIdentity)(nil), "akash.inventory.v1.SoftwareIdentity")
	proto.RegisterType((*SnapshotResourceSummary)(nil), "akash.inventory.v1.SnapshotResourceSummary")
	proto.RegisterType((*SnapshotEvidenceSection)(nil), "akash.inventory.v1.SnapshotEvidenceSection")
	proto.RegisterType((*GetInventorySnapshotRequest)(nil), "akash.inventory.v1.GetInventorySnapshotRequest")
	proto.RegisterType((*GetInventorySnapshotResponse)(nil), "akash.inventory.v1.GetInventorySnapshotResponse")
	proto.RegisterType((*GetCommittedInventorySnapshotRequest)(nil), "akash.inventory.v1.GetCommittedInventorySnapshotRequest")
	proto.RegisterType((*GetCommittedInventorySnapshotResponse)(nil), "akash.inventory.v1.GetCommittedInventorySnapshotResponse")
}

func init() { proto.RegisterFile("akash/inventory/v1/snapshot.proto", fileDescriptor_ad89c697cb83f0ea) }

var fileDescriptor_ad89c697cb83f0ea = []byte{
	// 1357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0xce, 0xa6, 0x69, 0x1c, 0x4f, 0xec, 0xd8, 0x1d, 0x42, 0xeb, 0x26, 0x6d, 0xc6, 0x19, 0x5a,
	0x91, 0x36, 0xc8, 0x6e, 0x1b, 0x55, 0x40, 0x91, 0x40, 0x75, 0xa8, 0x42, 0x28, 0x85, 0xb2, 0x09,
	0x15, 0xea, 0xc5, 0x1a, 0xaf, 0xc7, 0xf6, 0x2a, 0xde, 0x1f, 0xec, 0x8e, 0x8d, 0x7c, 0x42, 0x82,
	0x23, 0x07, 0x2a, 0x21, 0x24, 0x0e, 0xfc, 0x31, 0x70, 0xeb, 0xb1, 0x12, 0x17, 0x4e, 0x43, 0xe5,
	0x72, 0xf2, 0x71, 0x25, 0x0e, 0xdc, 0xd0, 0xce, 0xcc, 0xfe, 0xf0, 0xda, 0x6d, 0x81, 0x03, 0x37,
	0xcf, 0xf7, 0xbd, 0xf7, 0xbd, 0xb7, 0x33, 0xef, 0xbd, 0x19, 0x83, 0x6d, 0x72, 0x42, 0xfc, 0x5e,
	0xdd, 0xb4, 0x87, 0xd4, 0x66, 0x8e, 0x37, 0xaa, 0x0f, 0xaf, 0xd7, 0x7d, 0x9b, 0xb8, 0x7e, 0xcf,
	0x61, 0x35, 0xd7, 0x73, 0x98, 0x03, 0xa1, 0x30, 0xa9, 0xc5, 0x26, 0xb5, 0xe1, 0xf5, 0x8d, 0xf5,
	0xae, 0xd3, 0x75, 0x04, 0x5d, 0x0f, 0x7f, 0x49, 0xcb, 0x0d, 0xd4, 0x75, 0x9c, 0x6e, 0x9f, 0xd6,
	0xc5, 0xaa, 0x35, 0xe8, 0xd4, 0x99, 0x69, 0x51, 0x9f, 0x11, 0xcb, 0x55, 0x06, 0x17, 0x94, 0x01,
	0x71, 0xcd, 0x3a, 0xb1, 0x6d, 0x87, 0x11, 0x66, 0x3a, 0xb6, 0xaf, 0xd8, 0xea, 0x9c, 0x5c, 0x8c,
	0xfe, 0xc0, 0x67, 0xd4, 0x93, 0x16, 0xf8, 0xaf, 0xd3, 0xa0, 0x74, 0xa4, 0xb2, 0xbb, 0x4f, 0x46,
	0x7d, 0x87, 0xb4, 0xa1, 0x0e, 0xd6, 0x7c, 0xa3, 0x47, 0x2d, 0xd2, 0x1c, 0x52, 0xcf, 0x37, 0x1d,
	0xbb, 0xa2, 0x55, 0xb5, 0x9d, 0x62, 0x63, 0x77, 0xc2, 0x51, 0x86, 0x09, 0x38, 0x7a, 0x75, 0x44,
	0xac, 0xfe, 0x2d, 0x3c, 0x8d, 0x63, 0xbd, 0x28, 0x81, 0x07, 0x72, 0x0d, 0xdf, 0x01, 0x2b, 0xae,
	0xe7, 0x0c, 0xcd, 0x36, 0xf5, 0x2a, 0x8b, 0x55, 0x6d, 0x27, 0xdf, 0x40, 0x13, 0x8e, 0x62, 0x2c,
	0xe0, 0xa8, 0x24, 0x75, 0x22, 0x04, 0xeb, 0x31, 0x09, 0xef, 0x80, 0x15, 0xa3, 0x47, 0x4c, 0xbb,
	0x69, 0xb6, 0x2b, 0xa7, 0x84, 0xf3, 0xd5, 0x31, 0x47, 0xb9, 0xfd, 0x10, 0x3b, 0x7c, 0x3f, 0xd4,
	0x89, 0xe8, 0x44, 0x27, 0x42, 0xb0, 0x9e, 0x13, 0x3f, 0x0f, 0xdb, 0xb0, 0x0e, 0x4e, 0xdb, 0x8e,
	0x6d, 0xd0, 0xca, 0x52, 0x55, 0xdb, 0x29, 0x34, 0xce, 0x4f, 0x38, 0x92, 0x40, 0xc0, 0x51, 0x41,
	0x7a, 0x89, 0x25, 0xd6, 0x25, 0x0c, 0x0d, 0x90, 0x8f, 0xf7, 0xbb, 0x72, 0xba, 0xaa, 0xed, 0xac,
	0xde, 0xd8, 0xa8, 0xc9, 0x0d, 0xaf, 0x45, 0x27, 0x52, 0x3b, 0x8e, 0x2c, 0x1a, 0x57, 0x1e, 0x73,
	0xb4, 0x30, 0xe1, 0x28, 0x71, 0x0a, 0x38, 0x2a, 0x4b, 0xe1, 0x18, 0xc2, 0x8f, 0x7e, 0x47, 0x9a,
	0x9e, 0x98, 0xc0, 0xcf, 0x41, 0x4e, 0x1d, 0x49, 0x65, 0x59, 0x84, 0xd8, 0xac, 0xcd, 0x96, 0x47,
	0x6d, 0x5f, 0x9a, 0x34, 0xb6, 0x55, 0x8c, 0xc8, 0x27, 0xe0, 0x68, 0x4d, 0x7d, 0xb0, 0x04, 0xc2,
	0xef, 0x95, 0xbf, 0xe0, 0xb7, 0x1a, 0x28, 0x7b, 0xd4, 0x77, 0x06, 0x9e, 0x41, 0x9b, 0xfe, 0xc0,
	0xb2, 0x88, 0x37, 0xaa, 0xe4, 0x44, 0x8c, 0xdd, 0x79, 0x31, 0xa2, 0x3a, 0xd0, 0x95, 0xcf, 0x91,
	0x74, 0x69, 0xec, 0xa9, 0x98, 0x33, 0x62, 0x01, 0x47, 0xe7, 0x64, 0xf0, 0x2c, 0x83, 0xf5, 0x92,
	0x37, 0xad, 0x02, 0xbf, 0xd3, 0xc0, 0x19, 0x1a, 0x9e, 0xa7, 0x1d, 0x9a, 0x51, 0x43, 0xd4, 0x69,
	0x65, 0xa5, 0x7a, 0xea, 0x65, 0xe9, 0xdc, 0x51, 0x4e, 0x47, 0xd2, 0xa7, 0x71, 0x53, 0xa5, 0x33,
	0xab, 0x16, 0x70, 0x54, 0x91, 0xf9, 0xcc, 0x50, 0x58, 0x2f, 0xd3, 0x69, 0x1d, 0x1f, 0x3f, 0x5d,
	0x02, 0xe5, 0x23, 0xa7, 0xc3, 0xbe, 0x24, 0x1e, 0x3d, 0x6c, 0x53, 0x9b, 0x99, 0x6c, 0x04, 0xdf,
	0x04, 0xb9, 0x74, 0xd5, 0xe7, 0x1b, 0x17, 0xc3, 0xdd, 0x4e, 0xca, 0x5d, 0xed, 0x76, 0x5c, 0xe7,
	0x11, 0x05, 0x3f, 0x04, 0x05, 0xe2, 0x31, 0xb3, 0x43, 0x0c, 0xd6, 0xf4, 0x68, 0x47, 0x55, 0xf9,
	0xeb, 0x13, 0x8e, 0xa6, 0xf0, 0x80, 0xa3, 0x57, 0xa4, 0x44, 0x1a, 0xc5, 0xfa, 0x6a, 0xb4, 0xd4,
	0x69, 0x07, 0x3e, 0x04, 0xe5, 0xb6, 0xd9, 0xa5, 0x3e, 0x6b, 0x92, 0x7e, 0xd7, 0xf1, 0x4c, 0xd6,
	0xb3, 0x54, 0xe1, 0xd7, 0xc3, 0x73, 0xc8, 0x72, 0xc9, 0x39, 0x64, 0x19, 0xac, 0x97, 0x24, 0x74,
	0x3b, 0x42, 0xe0, 0x1e, 0x58, 0x96, 0x90, 0x6a, 0x83, 0xcd, 0x09, 0x47, 0x0a, 0x09, 0x38, 0x2a,
	0xa6, 0x75, 0xb0, 0xae, 0x08, 0x31, 0x12, 0xcc, 0xae, 0x4d, 0xd8, 0xc0, 0xa3, 0x4d, 0x36, 0x72,
	0xa9, 0x68, 0x87, 0xbc, 0x1a, 0x09, 0x53, 0x4c, 0x6a, 0x24, 0x4c, 0xe1, 0xe1, 0x48, 0x88, 0x80,
	0xe3, 0x91, 0x4b, 0xe1, 0x7b, 0x20, 0x1f, 0x03, 0xa2, 0xf4, 0x0b, 0x8d, 0xed, 0xb0, 0x7b, 0x62,
	0x30, 0xe9, 0x9e, 0x18, 0xc2, 0x7a, 0x42, 0xc3, 0x8f, 0x41, 0xa2, 0x28, 0xb6, 0x3c, 0x27, 0x72,
	0xba, 0x32, 0xe1, 0x68, 0x9a, 0x08, 0x38, 0x5a, 0xcf, 0xa6, 0x24, 0x36, 0xbd, 0x10, 0xaf, 0xc3,
	0x5d, 0xff, 0x14, 0xac, 0xb9, 0x83, 0x56, 0xdf, 0x34, 0x9a, 0x27, 0x74, 0x24, 0x04, 0x57, 0x92,
	0x8f, 0x9c, 0x66, 0x92, 0x8f, 0x9c, 0xc6, 0xb1, 0x5e, 0x90, 0xc0, 0x5d, 0x3a, 0xd2, 0x69, 0x07,
	0xff, 0xbc, 0x0c, 0xce, 0x3d, 0xa7, 0xad, 0xe0, 0x27, 0x00, 0x30, 0x87, 0x91, 0x7e, 0xb3, 0xeb,
	0x0e, 0x7c, 0x35, 0x62, 0xaf, 0x8d, 0x39, 0xca, 0x1f, 0x87, 0xe8, 0xc1, 0xfd, 0xcf, 0xfc, 0x09,
	0x47, 0x29, 0x93, 0x80, 0xa3, 0x33, 0x6a, 0x98, 0xc4, 0x18, 0xd6, 0xf3, 0x62, 0x71, 0xe0, 0x0e,
	0x7c, 0x78, 0x0c, 0x56, 0x25, 0x33, 0x34, 0x42, 0xc5, 0x45, 0xa1, 0xb8, 0x37, 0xe6, 0x08, 0x08,
	0xc5, 0x07, 0xfb, 0x52, 0x32, 0x6d, 0x14, 0x70, 0x04, 0xd3, 0x9a, 0x02, 0xc4, 0xba, 0x8c, 0xfa,
	0x20, 0x5c, 0xc0, 0x0e, 0x28, 0x49, 0xce, 0xa2, 0x96, 0xe3, 0x8d, 0x9a, 0x56, 0x4b, 0x94, 0xe2,
	0x52, 0xe3, 0xdd, 0x31, 0x47, 0x45, 0xa1, 0x7c, 0x4f, 0x30, 0xf7, 0x1a, 0x13, 0x8e, 0xb2, 0xb6,
	0x01, 0x47, 0x67, 0xd3, 0x01, 0x62, 0x02, 0xeb, 0x45, 0x96, 0xf2, 0x6d, 0xc1, 0x13, 0x50, 0x96,
	0x26, 0x3e, 0x73, 0x3c, 0xd2, 0xa5, 0x61, 0xa0, 0x25, 0x11, 0xe8, 0xf6, 0x98, 0xa3, 0x35, 0x11,
	0xe8, 0x48, 0x52, 0x22, 0xd2, 0x8c, 0x75, 0xd2, 0x05, 0x59, 0x06, 0xeb, 0x6b, 0x2c, 0xed, 0xde,
	0x0a, 0x4b, 0x87, 0x18, 0xcc, 0x1c, 0xd2, 0x66, 0x9f, 0x12, 0x9f, 0xfa, 0xa2, 0x9c, 0x8b, 0xb2,
	0x74, 0xa6, 0x88, 0xa4, 0x74, 0xa6, 0x60, 0xac, 0x17, 0xe4, 0xfa, 0x23, 0xb1, 0x0c, 0x1b, 0xd6,
	0x57, 0x93, 0x24, 0xbe, 0x34, 0x97, 0x93, 0x86, 0xcd, 0x72, 0x49, 0xaa, 0x59, 0x06, 0xeb, 0xa5,
	0x08, 0x8a, 0xae, 0xce, 0x16, 0x80, 0xb1, 0x55, 0xd2, 0x30, 0x39, 0xd1, 0x30, 0x7b, 0x13, 0x8e,
	0xe6, 0xb0, 0x01, 0x47, 0xe7, 0x33, 0xfa, 0xa9, 0x16, 0x3a, 0x13, 0x81, 0x47, 0x71, 0x2b, 0xfd,
	0xa8, 0x81, 0x18, 0x6d, 0x9a, 0x6a, 0x16, 0x8a, 0xf2, 0x5f, 0xbd, 0x71, 0x69, 0xee, 0x70, 0xce,
	0xcc, 0xcd, 0xc6, 0x9d, 0x09, 0x47, 0x9b, 0x33, 0x12, 0x6f, 0x38, 0x96, 0xc9, 0xa8, 0xe5, 0xb2,
	0xf0, 0xae, 0xc0, 0x99, 0x94, 0x66, 0x8d, 0xb0, 0x1e, 0x6f, 0x55, 0x24, 0x8c, 0xbf, 0x4a, 0x3a,
	0x28, 0x73, 0x13, 0xc0, 0x5d, 0xb0, 0x64, 0x13, 0x8b, 0xaa, 0x41, 0x7d, 0x6e, 0xc2, 0x91, 0x58,
	0x07, 0x1c, 0xad, 0xaa, 0xeb, 0x9c, 0x58, 0x14, 0xeb, 0x02, 0x0c, 0x07, 0xbb, 0x2b, 0x1f, 0x38,
	0xa2, 0x33, 0x0a, 0x72, 0xb0, 0x2b, 0x28, 0x19, 0xec, 0x0a, 0xc0, 0x7a, 0x44, 0xe1, 0x3d, 0xb0,
	0x79, 0x40, 0xd9, 0x61, 0xf4, 0xf5, 0x49, 0x3b, 0x7f, 0x31, 0x08, 0x47, 0xe3, 0x7a, 0xf4, 0xaa,
	0x08, 0xb3, 0x28, 0xa8, 0xa7, 0x03, 0xfe, 0x46, 0x03, 0x17, 0xe6, 0x7b, 0xf9, 0xae, 0x63, 0xfb,
	0x14, 0x5e, 0x01, 0xe5, 0xe8, 0x55, 0xd8, 0x8c, 0xf2, 0x92, 0x0a, 0x25, 0x3f, 0xf3, 0x1e, 0xbb,
	0x90, 0x1e, 0x94, 0x22, 0xf7, 0xf4, 0x14, 0xdc, 0x48, 0xbd, 0xac, 0xc4, 0x1d, 0x91, 0x3c, 0x9c,
	0xf0, 0x5d, 0x70, 0xe9, 0x80, 0xb2, 0x7d, 0xc7, 0xb2, 0x4c, 0xc6, 0x68, 0xfb, 0xb9, 0xdf, 0xf0,
	0x1a, 0x28, 0xc6, 0xc9, 0xf4, 0x88, 0xdf, 0x53, 0x99, 0x14, 0x22, 0xf0, 0x03, 0xe2, 0xf7, 0xf0,
	0x0f, 0x8b, 0xe0, 0xf2, 0x4b, 0xd4, 0xfe, 0xc7, 0x6f, 0x9b, 0xcd, 0x79, 0x69, 0x36, 0x67, 0xd8,
	0x02, 0x79, 0xd7, 0xf1, 0x19, 0x6d, 0x37, 0x09, 0xfb, 0x37, 0x2f, 0xb8, 0xd8, 0x29, 0xb9, 0x83,
	0x62, 0x48, 0xbe, 0xe0, 0x56, 0xe4, 0xfa, 0x36, 0xbb, 0xf1, 0xe7, 0x22, 0x28, 0x27, 0x7b, 0x41,
	0xbd, 0xa1, 0x69, 0x50, 0xf8, 0x93, 0x06, 0xd6, 0xe7, 0x9d, 0x3f, 0xac, 0xcf, 0xeb, 0xa6, 0x17,
	0xd4, 0xd7, 0xc6, 0xb5, 0x7f, 0xee, 0x20, 0xb7, 0x1f, 0x6f, 0x7f, 0xfd, 0xeb, 0x1f, 0xdf, 0x2f,
	0x6e, 0xde, 0xd2, 0xae, 0xe2, 0xb3, 0xe1, 0x8b, 0x3f, 0x79, 0xfe, 0x47, 0x7b, 0x03, 0x7f, 0xd1,
	0xc0, 0xc5, 0x17, 0x9e, 0x25, 0x7c, 0xeb, 0x39, 0x61, 0x5f, 0x5a, 0x4c, 0x1b, 0x6f, 0xff, 0x07,
	0x4f, 0x95, 0xf9, 0xae, 0xc8, 0xfc, 0x72, 0x98, 0x79, 0x75, 0x7e, 0xe6, 0x75, 0x23, 0x52, 0x69,
	0xdc, 0x7c, 0x3c, 0xde, 0xd2, 0x9e, 0x8c, 0xb7, 0xb4, 0xa7, 0xe3, 0x2d, 0xed, 0xd1, 0xb3, 0xad,
	0x85, 0x27, 0xcf, 0xb6, 0x16, 0x7e, 0x7b, 0xb6, 0xb5, 0xf0, 0x70, 0xd3, 0x3d, 0xe9, 0xd6, 0xc8,
	0x09, 0xab, 0xb5, 0xe9, 0xb0, 0xde, 0x75, 0xa6, 0xfe, 0xff, 0xb4, 0x96, 0xc5, 0xb9, 0xef, 0xfd,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xa3, 0xdd, 0xad, 0xa8, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InventoryServiceClient interface {
	// GetInventorySnapshot returns a fresh provider-signed live challenge snapshot.
	GetInventorySnapshot(ctx context.Context, in *GetInventorySnapshotRequest, opts ...grpc.CallOption) (*GetInventorySnapshotResponse, error)
	// GetCommittedInventorySnapshot returns an exact provider-signed committed
	// snapshot payload by hash, or the latest committed snapshot when no hash is
	// provided.
	GetCommittedInventorySnapshot(ctx context.Context, in *GetCommittedInventorySnapshotRequest, opts ...grpc.CallOption) (*GetCommittedInventorySnapshotResponse, error)
}

type inventoryServiceClient struct {
	cc grpc1.ClientConn
}

func NewInventoryServiceClient(cc grpc1.ClientConn) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) GetInventorySnapshot(ctx context.Context, in *GetInventorySnapshotRequest, opts ...grpc.CallOption) (*GetInventorySnapshotResponse, error) {
	out := new(GetInventorySnapshotResponse)
	err := c.cc.Invoke(ctx, "/akash.inventory.v1.InventoryService/GetInventorySnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetCommittedInventorySnapshot(ctx context.Context, in *GetCommittedInventorySnapshotRequest, opts ...grpc.CallOption) (*GetCommittedInventorySnapshotResponse, error) {
	out := new(GetCommittedInventorySnapshotResponse)
	err := c.cc.Invoke(ctx, "/akash.inventory.v1.InventoryService/GetCommittedInventorySnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
type InventoryServiceServer interface {
	// GetInventorySnapshot returns a fresh provider-signed live challenge snapshot.
	GetInventorySnapshot(context.Context, *GetInventorySnapshotRequest) (*GetInventorySnapshotResponse, error)
	// GetCommittedInventorySnapshot returns an exact provider-signed committed
	// snapshot payload by hash, or the latest committed snapshot when no hash is
	// provided.
	GetCommittedInventorySnapshot(context.Context, *GetCommittedInventorySnapshotRequest) (*GetCommittedInventorySnapshotResponse, error)
}

// UnimplementedInventoryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedInventoryServiceServer struct {
}

func (*UnimplementedInventoryServiceServer) GetInventorySnapshot(ctx context.Context, req *GetInventorySnapshotRequest) (*GetInventorySnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInventorySnapshot not implemented")
}
func (*UnimplementedInventoryServiceServer) GetCommittedInventorySnapshot(ctx context.Context, req *GetCommittedInventorySnapshotRequest) (*GetCommittedInventorySnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommittedInventorySnapshot not implemented")
}

func RegisterInventoryServiceServer(s grpc1.Server, srv InventoryServiceServer) {
	s.RegisterService(&_InventoryService_serviceDesc, srv)
}

func _InventoryService_GetInventorySnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventorySnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetInventorySnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/akash.inventory.v1.InventoryService/GetInventorySnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetInventorySnapshot(ctx, req.(*GetInventorySnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetCommittedInventorySnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommittedInventorySnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetCommittedInventorySnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/akash.inventory.v1.InventoryService/GetCommittedInventorySnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetCommittedInventorySnapshot(ctx, req.(*GetCommittedInventorySnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var InventoryService_serviceDesc = _InventoryService_serviceDesc
var _InventoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "akash.inventory.v1.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInventorySnapshot",
			Handler:    _InventoryService_GetInventorySnapshot_Handler,
		},
		{
			MethodName: "GetCommittedInventorySnapshot",
			Handler:    _InventoryService_GetCommittedInventorySnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "akash/inventory/v1/snapshot.proto",
}

func (m *SnapshotPayload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SnapshotPayload) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SnapshotPayload) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EvidenceSections) > 0 {
		for iNdEx := len(m.EvidenceSections) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EvidenceSections[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSnapshot(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	{
		size, err := m.ResourceSummary.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSnapshot(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.Cluster.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSnapshot(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.Timestamp, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Timestamp):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintSnapshot(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x2a
	if len(m.Nonce) > 0 {
		i -= len(m.Nonce)
		copy(dAtA[i:], m.Nonce)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.Nonce)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ChainID) > 0 {
		i -= len(m.ChainID)
		copy(dAtA[i:], m.ChainID)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.ChainID)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Provider) > 0 {
		i -= len(m.Provider)
		copy(dAtA[i:], m.Provider)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.Provider)))
		i--
		dAtA[i] = 0x12
	}
	if m.SchemaVersion != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.SchemaVersion))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SoftwareIdentity) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SoftwareIdentity) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SoftwareIdentity) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PublicKeyRef) > 0 {
		i -= len(m.PublicKeyRef)
		copy(dAtA[i:], m.PublicKeyRef)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.PublicKeyRef)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.SignatureRef) > 0 {
		i -= len(m.SignatureRef)
		copy(dAtA[i:], m.SignatureRef)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.SignatureRef)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.SignatureType) > 0 {
		i -= len(m.SignatureType)
		copy(dAtA[i:], m.SignatureType)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.SignatureType)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Digest) > 0 {
		i -= len(m.Digest)
		copy(dAtA[i:], m.Digest)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.Digest)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.DigestAlgorithm) > 0 {
		i -= len(m.DigestAlgorithm)
		copy(dAtA[i:], m.DigestAlgorithm)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.DigestAlgorithm)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ArtifactRef) > 0 {
		i -= len(m.ArtifactRef)
		copy(dAtA[i:], m.ArtifactRef)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.ArtifactRef)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SnapshotResourceSummary) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SnapshotResourceSummary) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SnapshotResourceSummary) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SoftwareIdentity != nil {
		{
			size, err := m.SoftwareIdentity.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSnapshot(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if len(m.SoftwareSignature) > 0 {
		i -= len(m.SoftwareSignature)
		copy(dAtA[i:], m.SoftwareSignature)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.SoftwareSignature)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.SoftwareVersion) > 0 {
		i -= len(m.SoftwareVersion)
		copy(dAtA[i:], m.SoftwareVersion)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.SoftwareVersion)))
		i--
		dAtA[i] = 0x32
	}
	if m.ActiveLeases != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.ActiveLeases))
		i--
		dAtA[i] = 0x28
	}
	if m.TotalStorageMB != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.TotalStorageMB))
		i--
		dAtA[i] = 0x20
	}
	if m.TotalMemoryMB != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.TotalMemoryMB))
		i--
		dAtA[i] = 0x18
	}
	if m.TotalVCPUs != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.TotalVCPUs))
		i--
		dAtA[i] = 0x10
	}
	if m.TotalGPUs != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.TotalGPUs))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SnapshotEvidenceSection) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SnapshotEvidenceSection) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SnapshotEvidenceSection) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Payload) > 0 {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetInventorySnapshotRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetInventorySnapshotRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetInventorySnapshotRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Nonce) > 0 {
		i -= len(m.Nonce)
		copy(dAtA[i:], m.Nonce)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.Nonce)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetInventorySnapshotResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetInventorySnapshotResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetInventorySnapshotResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Provider) > 0 {
		i -= len(m.Provider)
		copy(dAtA[i:], m.Provider)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.Provider)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SnapshotPayload) > 0 {
		i -= len(m.SnapshotPayload)
		copy(dAtA[i:], m.SnapshotPayload)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.SnapshotPayload)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetCommittedInventorySnapshotRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetCommittedInventorySnapshotRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetCommittedInventorySnapshotRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SnapshotHash) > 0 {
		i -= len(m.SnapshotHash)
		copy(dAtA[i:], m.SnapshotHash)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.SnapshotHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetCommittedInventorySnapshotResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetCommittedInventorySnapshotResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetCommittedInventorySnapshotResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n5, err5 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.PostedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.PostedAt):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintSnapshot(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x2a
	if len(m.SnapshotHash) > 0 {
		i -= len(m.SnapshotHash)
		copy(dAtA[i:], m.SnapshotHash)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.SnapshotHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Provider) > 0 {
		i -= len(m.Provider)
		copy(dAtA[i:], m.Provider)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.Provider)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SnapshotPayload) > 0 {
		i -= len(m.SnapshotPayload)
		copy(dAtA[i:], m.SnapshotPayload)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.SnapshotPayload)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSnapshot(dAtA []byte, offset int, v uint64) int {
	offset -= sovSnapshot(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SnapshotPayload) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SchemaVersion != 0 {
		n += 1 + sovSnapshot(uint64(m.SchemaVersion))
	}
	l = len(m.Provider)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	l = len(m.ChainID)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	l = len(m.Nonce)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Timestamp)
	n += 1 + l + sovSnapshot(uint64(l))
	l = m.Cluster.Size()
	n += 1 + l + sovSnapshot(uint64(l))
	l = m.ResourceSummary.Size()
	n += 1 + l + sovSnapshot(uint64(l))
	if len(m.EvidenceSections) > 0 {
		for _, e := range m.EvidenceSections {
			l = e.Size()
			n += 1 + l + sovSnapshot(uint64(l))
		}
	}
	return n
}

func (m *SoftwareIdentity) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	l = len(m.ArtifactRef)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	l = len(m.DigestAlgorithm)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	l = len(m.Digest)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	l = len(m.SignatureType)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	l = len(m.SignatureRef)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	l = len(m.PublicKeyRef)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	return n
}

func (m *SnapshotResourceSummary) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TotalGPUs != 0 {
		n += 1 + sovSnapshot(uint64(m.TotalGPUs))
	}
	if m.TotalVCPUs != 0 {
		n += 1 + sovSnapshot(uint64(m.TotalVCPUs))
	}
	if m.TotalMemoryMB != 0 {
		n += 1 + sovSnapshot(uint64(m.TotalMemoryMB))
	}
	if m.TotalStorageMB != 0 {
		n += 1 + sovSnapshot(uint64(m.TotalStorageMB))
	}
	if m.ActiveLeases != 0 {
		n += 1 + sovSnapshot(uint64(m.ActiveLeases))
	}
	l = len(m.SoftwareVersion)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	l = len(m.SoftwareSignature)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	if m.SoftwareIdentity != nil {
		l = m.SoftwareIdentity.Size()
		n += 1 + l + sovSnapshot(uint64(l))
	}
	return n
}

func (m *SnapshotEvidenceSection) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	return n
}

func (m *GetInventorySnapshotRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Nonce)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	return n
}

func (m *GetInventorySnapshotResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SnapshotPayload)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	l = len(m.Provider)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	return n
}

func (m *GetCommittedInventorySnapshotRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SnapshotHash)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	return n
}

func (m *GetCommittedInventorySnapshotResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SnapshotPayload)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	l = len(m.Provider)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	l = len(m.SnapshotHash)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.PostedAt)
	n += 1 + l + sovSnapshot(uint64(l))
	return n
}

func sovSnapshot(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSnapshot(x uint64) (n int) {
	return sovSnapshot(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SnapshotPayload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapshot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SnapshotPayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SnapshotPayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SchemaVersion", wireType)
			}
			m.SchemaVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SchemaVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Provider = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nonce = append(m.Nonce[:0], dAtA[iNdEx:postIndex]...)
			if m.Nonce == nil {
				m.Nonce = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.Timestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cluster", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Cluster.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceSummary", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ResourceSummary.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceSections", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvidenceSections = append(m.EvidenceSections, SnapshotEvidenceSection{})
			if err := m.EvidenceSections[len(m.EvidenceSections)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSnapshot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSnapshot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SoftwareIdentity) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapshot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SoftwareIdentity: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SoftwareIdentity: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ArtifactRef", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ArtifactRef = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DigestAlgorithm", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DigestAlgorithm = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Digest", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Digest = append(m.Digest[:0], dAtA[iNdEx:postIndex]...)
			if m.Digest == nil {
				m.Digest = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignatureType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignatureType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignatureRef", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignatureRef = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKeyRef", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKeyRef = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSnapshot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSnapshot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SnapshotResourceSummary) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapshot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SnapshotResourceSummary: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SnapshotResourceSummary: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalGPUs", wireType)
			}
			m.TotalGPUs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalGPUs |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalVCPUs", wireType)
			}
			m.TotalVCPUs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalVCPUs |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalMemoryMB", wireType)
			}
			m.TotalMemoryMB = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalMemoryMB |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalStorageMB", wireType)
			}
			m.TotalStorageMB = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalStorageMB |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveLeases", wireType)
			}
			m.ActiveLeases = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActiveLeases |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SoftwareVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SoftwareVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SoftwareSignature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SoftwareSignature = append(m.SoftwareSignature[:0], dAtA[iNdEx:postIndex]...)
			if m.SoftwareSignature == nil {
				m.SoftwareSignature = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SoftwareIdentity", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SoftwareIdentity == nil {
				m.SoftwareIdentity = &SoftwareIdentity{}
			}
			if err := m.SoftwareIdentity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSnapshot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSnapshot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SnapshotEvidenceSection) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapshot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SnapshotEvidenceSection: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SnapshotEvidenceSection: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSnapshot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSnapshot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetInventorySnapshotRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapshot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetInventorySnapshotRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetInventorySnapshotRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nonce = append(m.Nonce[:0], dAtA[iNdEx:postIndex]...)
			if m.Nonce == nil {
				m.Nonce = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSnapshot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSnapshot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetInventorySnapshotResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapshot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetInventorySnapshotResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetInventorySnapshotResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SnapshotPayload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SnapshotPayload = append(m.SnapshotPayload[:0], dAtA[iNdEx:postIndex]...)
			if m.SnapshotPayload == nil {
				m.SnapshotPayload = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Provider = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSnapshot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSnapshot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetCommittedInventorySnapshotRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapshot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetCommittedInventorySnapshotRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetCommittedInventorySnapshotRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SnapshotHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SnapshotHash = append(m.SnapshotHash[:0], dAtA[iNdEx:postIndex]...)
			if m.SnapshotHash == nil {
				m.SnapshotHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSnapshot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSnapshot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetCommittedInventorySnapshotResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapshot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetCommittedInventorySnapshotResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetCommittedInventorySnapshotResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SnapshotPayload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SnapshotPayload = append(m.SnapshotPayload[:0], dAtA[iNdEx:postIndex]...)
			if m.SnapshotPayload == nil {
				m.SnapshotPayload = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Provider = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SnapshotHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SnapshotHash = append(m.SnapshotHash[:0], dAtA[iNdEx:postIndex]...)
			if m.SnapshotHash == nil {
				m.SnapshotHash = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.PostedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSnapshot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSnapshot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSnapshot(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSnapshot
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSnapshot
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSnapshot
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSnapshot
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSnapshot        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSnapshot          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSnapshot = fmt.Errorf("proto: unexpected end of group")
)
