// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/oracle/v1/events.proto

package v1

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventPriceData is emitted when new price data is added to the oracle
type EventPriceData struct {
	// source is the address of the price source (oracle provider)
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source" yaml:"source"`
	// id identifies the price pair (denom and base_denom)
	Id DataID `protobuf:"bytes,2,opt,name=id,proto3" json:"id" yaml:"id"`
	// data contains the price value and timestamp
	Data PriceDataState `protobuf:"bytes,3,opt,name=data,proto3" json:"data" yaml:"data"`
}

func (m *EventPriceData) Reset()         { *m = EventPriceData{} }
func (m *EventPriceData) String() string { return proto.CompactTextString(m) }
func (*EventPriceData) ProtoMessage()    {}
func (*EventPriceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_209aa80654da7768, []int{0}
}
func (m *EventPriceData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventPriceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventPriceData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventPriceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventPriceData.Merge(m, src)
}
func (m *EventPriceData) XXX_Size() int {
	return m.Size()
}
func (m *EventPriceData) XXX_DiscardUnknown() {
	xxx_messageInfo_EventPriceData.DiscardUnknown(m)
}

var xxx_messageInfo_EventPriceData proto.InternalMessageInfo

func (m *EventPriceData) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *EventPriceData) GetId() DataID {
	if m != nil {
		return m.Id
	}
	return DataID{}
}

func (m *EventPriceData) GetData() PriceDataState {
	if m != nil {
		return m.Data
	}
	return PriceDataState{}
}

// EventPriceStaleWarning is emitted when price has not been updated and is about to become stale
type EventPriceStaleWarning struct {
	// source is the address of the price source
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source" yaml:"source"`
	// id identifies the price pair
	Id DataID `protobuf:"bytes,2,opt,name=id,proto3" json:"id" yaml:"id"`
	// last_height is the block height when the price was last updated
	LastHeight int64 `protobuf:"varint,3,opt,name=last_height,json=lastHeight,proto3" json:"last_height" yaml:"last_height"`
	// blocks_to_stall is the number of blocks until the price becomes stale
	BlocksToStall int64 `protobuf:"varint,4,opt,name=blocks_to_stall,json=blocksToStall,proto3" json:"blocks_to_stall" yaml:"blocks_to_stall"`
}

func (m *EventPriceStaleWarning) Reset()         { *m = EventPriceStaleWarning{} }
func (m *EventPriceStaleWarning) String() string { return proto.CompactTextString(m) }
func (*EventPriceStaleWarning) ProtoMessage()    {}
func (*EventPriceStaleWarning) Descriptor() ([]byte, []int) {
	return fileDescriptor_209aa80654da7768, []int{1}
}
func (m *EventPriceStaleWarning) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventPriceStaleWarning) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventPriceStaleWarning.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventPriceStaleWarning) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventPriceStaleWarning.Merge(m, src)
}
func (m *EventPriceStaleWarning) XXX_Size() int {
	return m.Size()
}
func (m *EventPriceStaleWarning) XXX_DiscardUnknown() {
	xxx_messageInfo_EventPriceStaleWarning.DiscardUnknown(m)
}

var xxx_messageInfo_EventPriceStaleWarning proto.InternalMessageInfo

func (m *EventPriceStaleWarning) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *EventPriceStaleWarning) GetId() DataID {
	if m != nil {
		return m.Id
	}
	return DataID{}
}

func (m *EventPriceStaleWarning) GetLastHeight() int64 {
	if m != nil {
		return m.LastHeight
	}
	return 0
}

func (m *EventPriceStaleWarning) GetBlocksToStall() int64 {
	if m != nil {
		return m.BlocksToStall
	}
	return 0
}

// EventPriceStaled is emitted when a price has become stale
type EventPriceStaled struct {
	// id identifies the price pair
	Id DataID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
	// last_height is the block height when the price was last updated before becoming stale
	LastHeight int64 `protobuf:"varint,2,opt,name=last_height,json=lastHeight,proto3" json:"last_height" yaml:"last_height"`
}

func (m *EventPriceStaled) Reset()         { *m = EventPriceStaled{} }
func (m *EventPriceStaled) String() string { return proto.CompactTextString(m) }
func (*EventPriceStaled) ProtoMessage()    {}
func (*EventPriceStaled) Descriptor() ([]byte, []int) {
	return fileDescriptor_209aa80654da7768, []int{2}
}
func (m *EventPriceStaled) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventPriceStaled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventPriceStaled.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventPriceStaled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventPriceStaled.Merge(m, src)
}
func (m *EventPriceStaled) XXX_Size() int {
	return m.Size()
}
func (m *EventPriceStaled) XXX_DiscardUnknown() {
	xxx_messageInfo_EventPriceStaled.DiscardUnknown(m)
}

var xxx_messageInfo_EventPriceStaled proto.InternalMessageInfo

func (m *EventPriceStaled) GetId() DataID {
	if m != nil {
		return m.Id
	}
	return DataID{}
}

func (m *EventPriceStaled) GetLastHeight() int64 {
	if m != nil {
		return m.LastHeight
	}
	return 0
}

// EventPriceRecovered is emitted when a stale price has started receiving updates again
type EventPriceRecovered struct {
	// id identifies the price pair
	Id DataID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
	// height is the block height when the price recovery was detected
	Height int64 `protobuf:"varint,2,opt,name=height,proto3" json:"height" yaml:"height"`
}

func (m *EventPriceRecovered) Reset()         { *m = EventPriceRecovered{} }
func (m *EventPriceRecovered) String() string { return proto.CompactTextString(m) }
func (*EventPriceRecovered) ProtoMessage()    {}
func (*EventPriceRecovered) Descriptor() ([]byte, []int) {
	return fileDescriptor_209aa80654da7768, []int{3}
}
func (m *EventPriceRecovered) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventPriceRecovered) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventPriceRecovered.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventPriceRecovered) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventPriceRecovered.Merge(m, src)
}
func (m *EventPriceRecovered) XXX_Size() int {
	return m.Size()
}
func (m *EventPriceRecovered) XXX_DiscardUnknown() {
	xxx_messageInfo_EventPriceRecovered.DiscardUnknown(m)
}

var xxx_messageInfo_EventPriceRecovered proto.InternalMessageInfo

func (m *EventPriceRecovered) GetId() DataID {
	if m != nil {
		return m.Id
	}
	return DataID{}
}

func (m *EventPriceRecovered) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

// EventAggregatedPrice is emitted when aggregated price has an update
type EventAggregatedPrice struct {
	Price AggregatedPrice `protobuf:"bytes,1,opt,name=price,proto3" json:"price" yaml:"price"`
}

func (m *EventAggregatedPrice) Reset()         { *m = EventAggregatedPrice{} }
func (m *EventAggregatedPrice) String() string { return proto.CompactTextString(m) }
func (*EventAggregatedPrice) ProtoMessage()    {}
func (*EventAggregatedPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_209aa80654da7768, []int{4}
}
func (m *EventAggregatedPrice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventAggregatedPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventAggregatedPrice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventAggregatedPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventAggregatedPrice.Merge(m, src)
}
func (m *EventAggregatedPrice) XXX_Size() int {
	return m.Size()
}
func (m *EventAggregatedPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_EventAggregatedPrice.DiscardUnknown(m)
}

var xxx_messageInfo_EventAggregatedPrice proto.InternalMessageInfo

func (m *EventAggregatedPrice) GetPrice() AggregatedPrice {
	if m != nil {
		return m.Price
	}
	return AggregatedPrice{}
}

func init() {
	proto.RegisterType((*EventPriceData)(nil), "akash.oracle.v1.EventPriceData")
	proto.RegisterType((*EventPriceStaleWarning)(nil), "akash.oracle.v1.EventPriceStaleWarning")
	proto.RegisterType((*EventPriceStaled)(nil), "akash.oracle.v1.EventPriceStaled")
	proto.RegisterType((*EventPriceRecovered)(nil), "akash.oracle.v1.EventPriceRecovered")
	proto.RegisterType((*EventAggregatedPrice)(nil), "akash.oracle.v1.EventAggregatedPrice")
}

func init() { proto.RegisterFile("akash/oracle/v1/events.proto", fileDescriptor_209aa80654da7768) }

var fileDescriptor_209aa80654da7768 = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xb1, 0x6e, 0x13, 0x31,
	0x18, 0x8e, 0xaf, 0xa5, 0x52, 0x1d, 0x4a, 0xd1, 0x11, 0xb5, 0xa1, 0xa5, 0xe7, 0xc8, 0x12, 0x52,
	0x97, 0xde, 0xa9, 0x64, 0x40, 0x62, 0xa2, 0xa7, 0x82, 0x40, 0x2c, 0xd5, 0x85, 0x0a, 0x89, 0x25,
	0x72, 0xcf, 0x96, 0x73, 0xca, 0x25, 0x8e, 0xce, 0x26, 0x12, 0xef, 0xc0, 0xc0, 0x03, 0xf0, 0x18,
	0x3c, 0x03, 0xea, 0x58, 0x31, 0x31, 0x59, 0x28, 0xd9, 0xb2, 0x71, 0x4f, 0x80, 0xce, 0x36, 0x4d,
	0xb9, 0x6c, 0xa8, 0x03, 0x9b, 0xbf, 0xef, 0xf3, 0xff, 0xfd, 0xdf, 0x6f, 0xd9, 0x86, 0x8f, 0xc8,
	0x90, 0xc8, 0x41, 0x24, 0x0a, 0x92, 0xe6, 0x2c, 0x9a, 0x1e, 0x47, 0x6c, 0xca, 0xc6, 0x4a, 0x86,
	0x93, 0x42, 0x28, 0xe1, 0x6f, 0x1b, 0x35, 0xb4, 0x6a, 0x38, 0x3d, 0xde, 0x5b, 0xd9, 0x3e, 0x29,
	0xb2, 0x94, 0xb9, 0xed, 0x7b, 0x2d, 0x2e, 0xb8, 0x30, 0xcb, 0xa8, 0x5a, 0x39, 0xf6, 0x61, 0x2a,
	0xe4, 0x48, 0xc8, 0xbe, 0x15, 0x2c, 0xb0, 0x12, 0xfe, 0x05, 0xe0, 0xbd, 0x17, 0x55, 0xc3, 0xb3,
	0xca, 0xe6, 0x94, 0x28, 0xe2, 0xbf, 0x81, 0x1b, 0x52, 0x7c, 0x28, 0x52, 0xd6, 0x06, 0x1d, 0x70,
	0xb8, 0x19, 0x77, 0x17, 0x1a, 0x39, 0xa6, 0xd4, 0x68, 0xeb, 0x23, 0x19, 0xe5, 0xcf, 0xb0, 0xc5,
	0xf8, 0xfb, 0xd7, 0xa3, 0x96, 0xf3, 0x3b, 0xa1, 0xb4, 0x60, 0x52, 0xf6, 0x54, 0x91, 0x8d, 0x79,
	0xe2, 0x0a, 0xfc, 0xe7, 0xd0, 0xcb, 0x68, 0xdb, 0xeb, 0x80, 0xc3, 0xe6, 0x93, 0xdd, 0xb0, 0x36,
	0x4c, 0x58, 0xf5, 0x7b, 0x7d, 0x1a, 0xef, 0x5e, 0x6a, 0xd4, 0x58, 0x68, 0xe4, 0x65, 0xb4, 0xd4,
	0x68, 0xd3, 0x76, 0xc8, 0x28, 0x4e, 0xbc, 0x8c, 0xfa, 0x67, 0x70, 0x9d, 0x12, 0x45, 0xda, 0x6b,
	0xc6, 0x03, 0xad, 0x78, 0x5c, 0x07, 0xef, 0x29, 0xa2, 0x58, 0xbc, 0xef, 0xbc, 0x4c, 0x51, 0xa9,
	0x51, 0xd3, 0xba, 0x55, 0x08, 0x27, 0x86, 0xc4, 0xdf, 0x3c, 0xb8, 0xb3, 0x9c, 0xb9, 0xa7, 0x48,
	0xce, 0xde, 0x91, 0x62, 0x9c, 0x8d, 0xf9, 0xff, 0x36, 0xfb, 0x4b, 0xd8, 0xcc, 0x89, 0x54, 0xfd,
	0x01, 0xcb, 0xf8, 0x40, 0x99, 0x23, 0x58, 0x8b, 0x1f, 0x2f, 0x34, 0xba, 0x49, 0x97, 0x1a, 0xf9,
	0xb6, 0xec, 0x06, 0x89, 0x13, 0x58, 0xa1, 0x57, 0x06, 0xf8, 0xe7, 0x70, 0xfb, 0x22, 0x17, 0xe9,
	0x50, 0xf6, 0x95, 0xe8, 0x4b, 0x45, 0xf2, 0xbc, 0xbd, 0x6e, 0xbc, 0x8e, 0x16, 0x1a, 0xd5, 0xa5,
	0x52, 0xa3, 0x1d, 0xeb, 0x57, 0x13, 0x70, 0xb2, 0x65, 0x99, 0xb7, 0xa2, 0x67, 0xf0, 0x17, 0x00,
	0xef, 0xd7, 0x0e, 0x92, 0xba, 0xa9, 0xc1, 0xed, 0x4d, 0xed, 0xfd, 0xe3, 0xd4, 0xf8, 0x13, 0x80,
	0x0f, 0x96, 0xf1, 0x12, 0x96, 0x8a, 0x29, 0x2b, 0x6e, 0x25, 0x61, 0x17, 0x6e, 0xfc, 0x15, 0x6e,
	0xbf, 0xba, 0x26, 0xd7, 0xb9, 0xdc, 0x35, 0xf9, 0x13, 0xc9, 0x09, 0x78, 0x04, 0x5b, 0x26, 0xcd,
	0x09, 0xe7, 0x05, 0xe3, 0x44, 0x31, 0x6a, 0x72, 0xf9, 0xe7, 0xf0, 0x8e, 0x79, 0xc3, 0x2e, 0x51,
	0x67, 0x25, 0x51, 0xad, 0x20, 0x3e, 0x70, 0xd1, 0x6c, 0x59, 0xa9, 0xd1, 0x5d, 0xdb, 0xd0, 0x40,
	0x9c, 0x58, 0x3a, 0x7e, 0x7a, 0x39, 0x0b, 0xc0, 0xd5, 0x2c, 0x00, 0x3f, 0x67, 0x01, 0xf8, 0x3c,
	0x0f, 0x1a, 0x57, 0xf3, 0xa0, 0xf1, 0x63, 0x1e, 0x34, 0xde, 0x1f, 0x4c, 0x86, 0x3c, 0x24, 0x43,
	0x15, 0x52, 0x36, 0x8d, 0xb8, 0x88, 0xc6, 0x82, 0xb2, 0xe5, 0x87, 0x72, 0xb1, 0x61, 0x7e, 0x86,
	0xee, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xec, 0xca, 0x23, 0x99, 0x04, 0x00, 0x00,
}

func (m *EventPriceData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventPriceData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventPriceData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Data.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Id.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Source) > 0 {
		i -= len(m.Source)
		copy(dAtA[i:], m.Source)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Source)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventPriceStaleWarning) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventPriceStaleWarning) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventPriceStaleWarning) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlocksToStall != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.BlocksToStall))
		i--
		dAtA[i] = 0x20
	}
	if m.LastHeight != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.LastHeight))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.Id.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Source) > 0 {
		i -= len(m.Source)
		copy(dAtA[i:], m.Source)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Source)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventPriceStaled) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventPriceStaled) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventPriceStaled) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastHeight != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.LastHeight))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.Id.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventPriceRecovered) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventPriceRecovered) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventPriceRecovered) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.Id.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventAggregatedPrice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventAggregatedPrice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventAggregatedPrice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Price.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventPriceData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Source)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = m.Id.Size()
	n += 1 + l + sovEvents(uint64(l))
	l = m.Data.Size()
	n += 1 + l + sovEvents(uint64(l))
	return n
}

func (m *EventPriceStaleWarning) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Source)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = m.Id.Size()
	n += 1 + l + sovEvents(uint64(l))
	if m.LastHeight != 0 {
		n += 1 + sovEvents(uint64(m.LastHeight))
	}
	if m.BlocksToStall != 0 {
		n += 1 + sovEvents(uint64(m.BlocksToStall))
	}
	return n
}

func (m *EventPriceStaled) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Id.Size()
	n += 1 + l + sovEvents(uint64(l))
	if m.LastHeight != 0 {
		n += 1 + sovEvents(uint64(m.LastHeight))
	}
	return n
}

func (m *EventPriceRecovered) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Id.Size()
	n += 1 + l + sovEvents(uint64(l))
	if m.Height != 0 {
		n += 1 + sovEvents(uint64(m.Height))
	}
	return n
}

func (m *EventAggregatedPrice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Price.Size()
	n += 1 + l + sovEvents(uint64(l))
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventPriceData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventPriceData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventPriceData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Id.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Data.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventPriceStaleWarning) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventPriceStaleWarning: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventPriceStaleWarning: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Id.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastHeight", wireType)
			}
			m.LastHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlocksToStall", wireType)
			}
			m.BlocksToStall = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlocksToStall |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventPriceStaled) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventPriceStaled: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventPriceStaled: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Id.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastHeight", wireType)
			}
			m.LastHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventPriceRecovered) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventPriceRecovered: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventPriceRecovered: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Id.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventAggregatedPrice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventAggregatedPrice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventAggregatedPrice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
