// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/manifest/v2beta3/httpoptions.proto

package v2beta3

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ProxyBuffering is a tri-state for expose.http_options.proxy_buffering.
// PROXY_BUFFERING_UNSPECIFIED (0) means the tenant did not set it and the
// provider applies the gateway default (nginx: on). It is omitempty so it never
// affects the manifest version hash of deployments that do not set it.
type ProxyBuffering int32

const (
	ProxyBufferingUnspecified ProxyBuffering = 0
	ProxyBufferingOn          ProxyBuffering = 1
	ProxyBufferingOff         ProxyBuffering = 2
)

var ProxyBuffering_name = map[int32]string{
	0: "PROXY_BUFFERING_UNSPECIFIED",
	1: "PROXY_BUFFERING_ON",
	2: "PROXY_BUFFERING_OFF",
}

var ProxyBuffering_value = map[string]int32{
	"PROXY_BUFFERING_UNSPECIFIED": 0,
	"PROXY_BUFFERING_ON":          1,
	"PROXY_BUFFERING_OFF":         2,
}

func (x ProxyBuffering) String() string {
	return proto.EnumName(ProxyBuffering_name, int32(x))
}

func (ProxyBuffering) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ee317fccaba20357, []int{0}
}

// ServiceExposeHTTPOptions
type ServiceExposeHTTPOptions struct {
	MaxBodySize uint32   `protobuf:"varint,1,opt,name=max_body_size,json=maxBodySize,proto3" json:"maxBodySize" yaml:"maxBodySize"`
	ReadTimeout uint32   `protobuf:"varint,2,opt,name=read_timeout,json=readTimeout,proto3" json:"readTimeout" yaml:"readTimeout"`
	SendTimeout uint32   `protobuf:"varint,3,opt,name=send_timeout,json=sendTimeout,proto3" json:"sendTimeout" yaml:"sendTimeout"`
	NextTries   uint32   `protobuf:"varint,4,opt,name=next_tries,json=nextTries,proto3" json:"nextTries" yaml:"nextTries"`
	NextTimeout uint32   `protobuf:"varint,5,opt,name=next_timeout,json=nextTimeout,proto3" json:"nextTimeout" yaml:"nextTimeout"`
	NextCases   []string `protobuf:"bytes,6,rep,name=next_cases,json=nextCases,proto3" json:"nextCases,omitempty" yaml:"nextCases,omitempty"`
	// New nginx proxy options (fields 7-12). All are omitempty so a manifest that
	// does not set them serializes identically to a pre-change manifest (unchanged
	// version hash / backward compatible with older providers). zero == unset.
	ProxyBuffering       ProxyBuffering `protobuf:"varint,7,opt,name=proxy_buffering,json=proxyBuffering,proto3,enum=akash.manifest.v2beta3.ProxyBuffering" json:"proxyBuffering,omitempty" yaml:"proxyBuffering,omitempty"`
	ProxyBufferSize      uint32         `protobuf:"varint,8,opt,name=proxy_buffer_size,json=proxyBufferSize,proto3" json:"proxyBufferSize,omitempty" yaml:"proxyBufferSize,omitempty"`
	ProxyBuffersNumber   uint32         `protobuf:"varint,9,opt,name=proxy_buffers_number,json=proxyBuffersNumber,proto3" json:"proxyBuffersNumber,omitempty" yaml:"proxyBuffersNumber,omitempty"`
	ProxyBuffersSize     uint32         `protobuf:"varint,10,opt,name=proxy_buffers_size,json=proxyBuffersSize,proto3" json:"proxyBuffersSize,omitempty" yaml:"proxyBuffersSize,omitempty"`
	ProxyBusyBuffersSize uint32         `protobuf:"varint,11,opt,name=proxy_busy_buffers_size,json=proxyBusyBuffersSize,proto3" json:"proxyBusyBuffersSize,omitempty" yaml:"proxyBusyBuffersSize,omitempty"`
	ProxyConnectTimeout  uint32         `protobuf:"varint,12,opt,name=proxy_connect_timeout,json=proxyConnectTimeout,proto3" json:"proxyConnectTimeout,omitempty" yaml:"proxyConnectTimeout,omitempty"`
}

func (m *ServiceExposeHTTPOptions) Reset()      { *m = ServiceExposeHTTPOptions{} }
func (*ServiceExposeHTTPOptions) ProtoMessage() {}
func (*ServiceExposeHTTPOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee317fccaba20357, []int{0}
}
func (m *ServiceExposeHTTPOptions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ServiceExposeHTTPOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ServiceExposeHTTPOptions.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ServiceExposeHTTPOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceExposeHTTPOptions.Merge(m, src)
}
func (m *ServiceExposeHTTPOptions) XXX_Size() int {
	return m.Size()
}
func (m *ServiceExposeHTTPOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceExposeHTTPOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceExposeHTTPOptions proto.InternalMessageInfo

func (m *ServiceExposeHTTPOptions) GetMaxBodySize() uint32 {
	if m != nil {
		return m.MaxBodySize
	}
	return 0
}

func (m *ServiceExposeHTTPOptions) GetReadTimeout() uint32 {
	if m != nil {
		return m.ReadTimeout
	}
	return 0
}

func (m *ServiceExposeHTTPOptions) GetSendTimeout() uint32 {
	if m != nil {
		return m.SendTimeout
	}
	return 0
}

func (m *ServiceExposeHTTPOptions) GetNextTries() uint32 {
	if m != nil {
		return m.NextTries
	}
	return 0
}

func (m *ServiceExposeHTTPOptions) GetNextTimeout() uint32 {
	if m != nil {
		return m.NextTimeout
	}
	return 0
}

func (m *ServiceExposeHTTPOptions) GetNextCases() []string {
	if m != nil {
		return m.NextCases
	}
	return nil
}

func (m *ServiceExposeHTTPOptions) GetProxyBuffering() ProxyBuffering {
	if m != nil {
		return m.ProxyBuffering
	}
	return ProxyBufferingUnspecified
}

func (m *ServiceExposeHTTPOptions) GetProxyBufferSize() uint32 {
	if m != nil {
		return m.ProxyBufferSize
	}
	return 0
}

func (m *ServiceExposeHTTPOptions) GetProxyBuffersNumber() uint32 {
	if m != nil {
		return m.ProxyBuffersNumber
	}
	return 0
}

func (m *ServiceExposeHTTPOptions) GetProxyBuffersSize() uint32 {
	if m != nil {
		return m.ProxyBuffersSize
	}
	return 0
}

func (m *ServiceExposeHTTPOptions) GetProxyBusyBuffersSize() uint32 {
	if m != nil {
		return m.ProxyBusyBuffersSize
	}
	return 0
}

func (m *ServiceExposeHTTPOptions) GetProxyConnectTimeout() uint32 {
	if m != nil {
		return m.ProxyConnectTimeout
	}
	return 0
}

func init() {
	proto.RegisterEnum("akash.manifest.v2beta3.ProxyBuffering", ProxyBuffering_name, ProxyBuffering_value)
	proto.RegisterType((*ServiceExposeHTTPOptions)(nil), "akash.manifest.v2beta3.ServiceExposeHTTPOptions")
}

func init() {
	proto.RegisterFile("akash/manifest/v2beta3/httpoptions.proto", fileDescriptor_ee317fccaba20357)
}

var fileDescriptor_ee317fccaba20357 = []byte{
	// 711 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x95, 0xcd, 0x4e, 0xdb, 0x4e,
	0x00, 0xc4, 0x63, 0xe0, 0xcf, 0xbf, 0x59, 0xbe, 0xc2, 0x12, 0x5a, 0x93, 0x16, 0x6f, 0x70, 0x4b,
	0x15, 0x55, 0xc8, 0x91, 0xe0, 0xd4, 0x1e, 0xda, 0x92, 0x34, 0x81, 0xa8, 0x52, 0x12, 0x99, 0x20,
	0xd1, 0x5e, 0x2c, 0x27, 0xd9, 0x04, 0x8b, 0xfa, 0xa3, 0x59, 0x83, 0x12, 0xa4, 0x4a, 0x55, 0x4f,
	0x15, 0x27, 0x5e, 0x80, 0x53, 0x5f, 0xa1, 0x0f, 0xc1, 0x11, 0xa9, 0x17, 0x4e, 0x56, 0x1b, 0x6e,
	0x3e, 0xf2, 0x04, 0x95, 0xd7, 0xa1, 0x5e, 0xdb, 0xe4, 0x16, 0xcd, 0xfc, 0x76, 0x66, 0x1c, 0xad,
	0x13, 0x90, 0x53, 0x8f, 0x54, 0x72, 0x98, 0xd7, 0x55, 0x43, 0xeb, 0x60, 0x62, 0xe7, 0x4f, 0x36,
	0x9b, 0xd8, 0x56, 0xb7, 0xf2, 0x87, 0xb6, 0x6d, 0x99, 0x96, 0xad, 0x99, 0x06, 0x91, 0xac, 0x9e,
	0x69, 0x9b, 0xf0, 0x21, 0x25, 0xa5, 0x3b, 0x52, 0x1a, 0x91, 0x99, 0x74, 0xd7, 0xec, 0x9a, 0x14,
	0xc9, 0x7b, 0x9f, 0x7c, 0x5a, 0xfc, 0x95, 0x04, 0xfc, 0x1e, 0xee, 0x9d, 0x68, 0x2d, 0x5c, 0xea,
	0x5b, 0x26, 0xc1, 0xbb, 0x8d, 0x46, 0xbd, 0xe6, 0x07, 0xc2, 0x0a, 0x98, 0xd3, 0xd5, 0xbe, 0xd2,
	0x34, 0xdb, 0x03, 0x85, 0x68, 0xa7, 0x98, 0xe7, 0xb2, 0x5c, 0x6e, 0xae, 0xb0, 0xee, 0x3a, 0x68,
	0x46, 0x57, 0xfb, 0x05, 0xb3, 0x3d, 0xd8, 0xd3, 0x4e, 0xf1, 0xad, 0x83, 0xe0, 0x40, 0xd5, 0x3f,
	0xbd, 0x12, 0x19, 0x51, 0x94, 0x59, 0x04, 0xee, 0x82, 0xd9, 0x1e, 0x56, 0xdb, 0x8a, 0xad, 0xe9,
	0xd8, 0x3c, 0xb6, 0xf9, 0x89, 0x20, 0xc9, 0xd3, 0x1b, 0xbe, 0x1c, 0x24, 0x31, 0xa2, 0x28, 0xb3,
	0x88, 0x97, 0x44, 0xb0, 0x11, 0x24, 0x4d, 0x06, 0x49, 0x9e, 0x1e, 0x4b, 0x62, 0x44, 0x51, 0x66,
	0x11, 0xf8, 0x16, 0x00, 0x03, 0xf7, 0x6d, 0xc5, 0xee, 0x69, 0x98, 0xf0, 0x53, 0x34, 0x67, 0xcd,
	0x75, 0x50, 0xd2, 0x53, 0x1b, 0x9e, 0x78, 0xeb, 0xa0, 0x94, 0x9f, 0xf2, 0x4f, 0x12, 0xe5, 0xc0,
	0xf6, 0xb6, 0xf8, 0x09, 0xa3, 0x2d, 0xff, 0x05, 0x5b, 0x28, 0x14, 0xdd, 0xc2, 0x88, 0xa2, 0xcc,
	0x22, 0xf0, 0x60, 0xb4, 0xa5, 0xa5, 0x12, 0x4c, 0xf8, 0xe9, 0xec, 0x64, 0x2e, 0x59, 0x78, 0x79,
	0xe9, 0x20, 0xce, 0x75, 0xd0, 0x92, 0xe7, 0x14, 0x3d, 0x63, 0xc3, 0xd4, 0x35, 0x1b, 0xeb, 0x96,
	0x3d, 0xb8, 0x75, 0x50, 0x26, 0xc8, 0x8c, 0x98, 0xa3, 0x8d, 0x54, 0x85, 0xe7, 0x1c, 0x58, 0xb0,
	0x7a, 0x66, 0x7f, 0xa0, 0x34, 0x8f, 0x3b, 0x1d, 0xdc, 0xd3, 0x8c, 0x2e, 0xff, 0x7f, 0x96, 0xcb,
	0xcd, 0x6f, 0x3e, 0x97, 0xee, 0xbf, 0x2a, 0x52, 0xdd, 0xc3, 0x0b, 0x77, 0x74, 0xe1, 0x8d, 0xeb,
	0x20, 0xde, 0x0a, 0x69, 0xa1, 0x21, 0xc8, 0x1f, 0x32, 0x8e, 0x10, 0xe5, 0xf9, 0xb0, 0x05, 0x75,
	0xb0, 0xc8, 0x2e, 0xf2, 0xef, 0xd6, 0x03, 0xfa, 0xdd, 0x6d, 0xbb, 0x0e, 0x5a, 0x61, 0x70, 0xef,
	0xf2, 0x84, 0xca, 0xb2, 0xb1, 0xb2, 0x30, 0x22, 0xca, 0x0b, 0x11, 0x0f, 0x0e, 0x40, 0x9a, 0xad,
	0x23, 0x8a, 0x71, 0xac, 0x37, 0x71, 0x8f, 0x4f, 0xd2, 0xc6, 0x1d, 0xd7, 0x41, 0x4f, 0x98, 0x23,
	0xa4, 0x4a, 0xdd, 0x50, 0xe9, 0xd3, 0x58, 0x69, 0x8c, 0x12, 0x65, 0x18, 0xb7, 0xe1, 0x67, 0x00,
	0xc3, 0xd5, 0xf4, 0x51, 0x01, 0x2d, 0x2e, 0xba, 0x0e, 0xca, 0xb0, 0x67, 0x62, 0xcf, 0xba, 0x16,
	0xaf, 0x8d, 0x3e, 0x6c, 0x2a, 0x6a, 0xc2, 0x6f, 0x1c, 0x78, 0x74, 0xd7, 0x49, 0x22, 0xc5, 0x33,
	0xb4, 0xf8, 0xbd, 0xeb, 0x20, 0x61, 0x74, 0x8e, 0x8c, 0x2d, 0x5f, 0x0f, 0x95, 0x93, 0x71, 0x03,
	0xd2, 0xf7, 0x01, 0xf0, 0x0b, 0x58, 0xf6, 0x37, 0xb4, 0x4c, 0xc3, 0xc0, 0xad, 0xe0, 0x0d, 0x99,
	0xa5, 0x0b, 0x2a, 0xae, 0x83, 0x56, 0x29, 0x50, 0xf4, 0xfd, 0xd1, 0x6b, 0x10, 0x1a, 0xf0, 0x8c,
	0x19, 0x30, 0x0e, 0x13, 0xe5, 0xa5, 0x7b, 0xfc, 0x17, 0x3f, 0x39, 0x30, 0x1f, 0xbe, 0xc4, 0xf0,
	0x35, 0x78, 0x5c, 0x97, 0x6b, 0x07, 0x1f, 0x94, 0xc2, 0x7e, 0xb9, 0x5c, 0x92, 0x2b, 0xd5, 0x1d,
	0x65, 0xbf, 0xba, 0x57, 0x2f, 0x15, 0x2b, 0xe5, 0x4a, 0xe9, 0x5d, 0x2a, 0x91, 0x59, 0x3d, 0xbb,
	0xc8, 0xae, 0x84, 0x0f, 0xed, 0x1b, 0xc4, 0xc2, 0x2d, 0xad, 0xa3, 0xe1, 0x36, 0xdc, 0x00, 0x30,
	0x7a, 0xbe, 0x56, 0x4d, 0x71, 0x99, 0xf4, 0xd9, 0x45, 0x36, 0x15, 0x3e, 0x56, 0x33, 0xa0, 0x04,
	0x96, 0x62, 0x74, 0xb9, 0x9c, 0x9a, 0xc8, 0x2c, 0x9f, 0x5d, 0x64, 0x17, 0x23, 0x78, 0xa7, 0x93,
	0x99, 0xfa, 0xfe, 0x43, 0x48, 0x14, 0xb6, 0xaf, 0xff, 0x08, 0x89, 0xaf, 0x43, 0x81, 0xbb, 0x1c,
	0x0a, 0xdc, 0xd5, 0x50, 0xe0, 0x7e, 0x0f, 0x05, 0xee, 0xfc, 0x46, 0x48, 0x5c, 0xdd, 0x08, 0x89,
	0xeb, 0x1b, 0x21, 0xf1, 0x11, 0x59, 0x47, 0x5d, 0x49, 0x3d, 0xb2, 0xa5, 0x36, 0x3e, 0xc9, 0x77,
	0xcd, 0xd8, 0xff, 0x41, 0x73, 0x9a, 0xfe, 0xac, 0x6f, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xe5,
	0x5d, 0xdc, 0x03, 0x30, 0x06, 0x00, 0x00,
}

func (m *ServiceExposeHTTPOptions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ServiceExposeHTTPOptions) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ServiceExposeHTTPOptions) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProxyConnectTimeout != 0 {
		i = encodeVarintHttpoptions(dAtA, i, uint64(m.ProxyConnectTimeout))
		i--
		dAtA[i] = 0x60
	}
	if m.ProxyBusyBuffersSize != 0 {
		i = encodeVarintHttpoptions(dAtA, i, uint64(m.ProxyBusyBuffersSize))
		i--
		dAtA[i] = 0x58
	}
	if m.ProxyBuffersSize != 0 {
		i = encodeVarintHttpoptions(dAtA, i, uint64(m.ProxyBuffersSize))
		i--
		dAtA[i] = 0x50
	}
	if m.ProxyBuffersNumber != 0 {
		i = encodeVarintHttpoptions(dAtA, i, uint64(m.ProxyBuffersNumber))
		i--
		dAtA[i] = 0x48
	}
	if m.ProxyBufferSize != 0 {
		i = encodeVarintHttpoptions(dAtA, i, uint64(m.ProxyBufferSize))
		i--
		dAtA[i] = 0x40
	}
	if m.ProxyBuffering != 0 {
		i = encodeVarintHttpoptions(dAtA, i, uint64(m.ProxyBuffering))
		i--
		dAtA[i] = 0x38
	}
	if len(m.NextCases) > 0 {
		for iNdEx := len(m.NextCases) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.NextCases[iNdEx])
			copy(dAtA[i:], m.NextCases[iNdEx])
			i = encodeVarintHttpoptions(dAtA, i, uint64(len(m.NextCases[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if m.NextTimeout != 0 {
		i = encodeVarintHttpoptions(dAtA, i, uint64(m.NextTimeout))
		i--
		dAtA[i] = 0x28
	}
	if m.NextTries != 0 {
		i = encodeVarintHttpoptions(dAtA, i, uint64(m.NextTries))
		i--
		dAtA[i] = 0x20
	}
	if m.SendTimeout != 0 {
		i = encodeVarintHttpoptions(dAtA, i, uint64(m.SendTimeout))
		i--
		dAtA[i] = 0x18
	}
	if m.ReadTimeout != 0 {
		i = encodeVarintHttpoptions(dAtA, i, uint64(m.ReadTimeout))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxBodySize != 0 {
		i = encodeVarintHttpoptions(dAtA, i, uint64(m.MaxBodySize))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintHttpoptions(dAtA []byte, offset int, v uint64) int {
	offset -= sovHttpoptions(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ServiceExposeHTTPOptions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxBodySize != 0 {
		n += 1 + sovHttpoptions(uint64(m.MaxBodySize))
	}
	if m.ReadTimeout != 0 {
		n += 1 + sovHttpoptions(uint64(m.ReadTimeout))
	}
	if m.SendTimeout != 0 {
		n += 1 + sovHttpoptions(uint64(m.SendTimeout))
	}
	if m.NextTries != 0 {
		n += 1 + sovHttpoptions(uint64(m.NextTries))
	}
	if m.NextTimeout != 0 {
		n += 1 + sovHttpoptions(uint64(m.NextTimeout))
	}
	if len(m.NextCases) > 0 {
		for _, s := range m.NextCases {
			l = len(s)
			n += 1 + l + sovHttpoptions(uint64(l))
		}
	}
	if m.ProxyBuffering != 0 {
		n += 1 + sovHttpoptions(uint64(m.ProxyBuffering))
	}
	if m.ProxyBufferSize != 0 {
		n += 1 + sovHttpoptions(uint64(m.ProxyBufferSize))
	}
	if m.ProxyBuffersNumber != 0 {
		n += 1 + sovHttpoptions(uint64(m.ProxyBuffersNumber))
	}
	if m.ProxyBuffersSize != 0 {
		n += 1 + sovHttpoptions(uint64(m.ProxyBuffersSize))
	}
	if m.ProxyBusyBuffersSize != 0 {
		n += 1 + sovHttpoptions(uint64(m.ProxyBusyBuffersSize))
	}
	if m.ProxyConnectTimeout != 0 {
		n += 1 + sovHttpoptions(uint64(m.ProxyConnectTimeout))
	}
	return n
}

func sovHttpoptions(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHttpoptions(x uint64) (n int) {
	return sovHttpoptions(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *ServiceExposeHTTPOptions) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ServiceExposeHTTPOptions{`,
		`MaxBodySize:` + fmt.Sprintf("%v", this.MaxBodySize) + `,`,
		`ReadTimeout:` + fmt.Sprintf("%v", this.ReadTimeout) + `,`,
		`SendTimeout:` + fmt.Sprintf("%v", this.SendTimeout) + `,`,
		`NextTries:` + fmt.Sprintf("%v", this.NextTries) + `,`,
		`NextTimeout:` + fmt.Sprintf("%v", this.NextTimeout) + `,`,
		`NextCases:` + fmt.Sprintf("%v", this.NextCases) + `,`,
		`ProxyBuffering:` + fmt.Sprintf("%v", this.ProxyBuffering) + `,`,
		`ProxyBufferSize:` + fmt.Sprintf("%v", this.ProxyBufferSize) + `,`,
		`ProxyBuffersNumber:` + fmt.Sprintf("%v", this.ProxyBuffersNumber) + `,`,
		`ProxyBuffersSize:` + fmt.Sprintf("%v", this.ProxyBuffersSize) + `,`,
		`ProxyBusyBuffersSize:` + fmt.Sprintf("%v", this.ProxyBusyBuffersSize) + `,`,
		`ProxyConnectTimeout:` + fmt.Sprintf("%v", this.ProxyConnectTimeout) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringHttpoptions(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *ServiceExposeHTTPOptions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHttpoptions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ServiceExposeHTTPOptions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ServiceExposeHTTPOptions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBodySize", wireType)
			}
			m.MaxBodySize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxBodySize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReadTimeout", wireType)
			}
			m.ReadTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReadTimeout |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendTimeout", wireType)
			}
			m.SendTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SendTimeout |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextTries", wireType)
			}
			m.NextTries = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextTries |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextTimeout", wireType)
			}
			m.NextTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextTimeout |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextCases", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHttpoptions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHttpoptions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NextCases = append(m.NextCases, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProxyBuffering", wireType)
			}
			m.ProxyBuffering = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProxyBuffering |= ProxyBuffering(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProxyBufferSize", wireType)
			}
			m.ProxyBufferSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProxyBufferSize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProxyBuffersNumber", wireType)
			}
			m.ProxyBuffersNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProxyBuffersNumber |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProxyBuffersSize", wireType)
			}
			m.ProxyBuffersSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProxyBuffersSize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProxyBusyBuffersSize", wireType)
			}
			m.ProxyBusyBuffersSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProxyBusyBuffersSize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProxyConnectTimeout", wireType)
			}
			m.ProxyConnectTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProxyConnectTimeout |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHttpoptions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHttpoptions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHttpoptions(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHttpoptions
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHttpoptions
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHttpoptions
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHttpoptions
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHttpoptions
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHttpoptions        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHttpoptions          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHttpoptions = fmt.Errorf("proto: unexpected end of group")
)
