// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/manifest/v2beta3/service.proto

package v2beta3

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	v1beta4 "pkg.akt.dev/go/node/types/resources/v1beta4"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// StorageParams
type StorageParams struct {
	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name" yaml:"name"`
	Mount    string `protobuf:"bytes,2,opt,name=mount,proto3" json:"mount" yaml:"mount"`
	ReadOnly bool   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"readOnly" yaml:"readOnly"`
}

func (m *StorageParams) Reset()      { *m = StorageParams{} }
func (*StorageParams) ProtoMessage() {}
func (*StorageParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d5964c4976d68e5, []int{0}
}
func (m *StorageParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StorageParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StorageParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StorageParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageParams.Merge(m, src)
}
func (m *StorageParams) XXX_Size() int {
	return m.Size()
}
func (m *StorageParams) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageParams.DiscardUnknown(m)
}

var xxx_messageInfo_StorageParams proto.InternalMessageInfo

func (m *StorageParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StorageParams) GetMount() string {
	if m != nil {
		return m.Mount
	}
	return ""
}

func (m *StorageParams) GetReadOnly() bool {
	if m != nil {
		return m.ReadOnly
	}
	return false
}

// ServicePermissions defines resource access permissions for the service.
// Resources map to Kubernetes RBAC permissions:
//   - logs
type ServicePermissions struct {
	Read []string `protobuf:"bytes,1,rep,name=read,proto3" json:"read,omitempty" yaml:"read,omitempty"`
}

func (m *ServicePermissions) Reset()      { *m = ServicePermissions{} }
func (*ServicePermissions) ProtoMessage() {}
func (*ServicePermissions) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d5964c4976d68e5, []int{1}
}
func (m *ServicePermissions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ServicePermissions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ServicePermissions.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ServicePermissions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServicePermissions.Merge(m, src)
}
func (m *ServicePermissions) XXX_Size() int {
	return m.Size()
}
func (m *ServicePermissions) XXX_DiscardUnknown() {
	xxx_messageInfo_ServicePermissions.DiscardUnknown(m)
}

var xxx_messageInfo_ServicePermissions proto.InternalMessageInfo

func (m *ServicePermissions) GetRead() []string {
	if m != nil {
		return m.Read
	}
	return nil
}

// AttestationParams controls attestation sidecar injection for confidential compute.
// When confidential-compute is enabled via placement attributes, the provider
// automatically injects an attestation sidecar. This message allows the tenant
// to opt out (e.g., when bringing their own attestation tooling).
type AttestationParams struct {
	// enabled controls whether the attestation sidecar is injected.
	// Defaults to true when confidential-compute is active.
	// Set to false to opt out of provider-managed attestation.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled" yaml:"enabled"`
}

func (m *AttestationParams) Reset()      { *m = AttestationParams{} }
func (*AttestationParams) ProtoMessage() {}
func (*AttestationParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d5964c4976d68e5, []int{2}
}
func (m *AttestationParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AttestationParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AttestationParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AttestationParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestationParams.Merge(m, src)
}
func (m *AttestationParams) XXX_Size() int {
	return m.Size()
}
func (m *AttestationParams) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestationParams.DiscardUnknown(m)
}

var xxx_messageInfo_AttestationParams proto.InternalMessageInfo

func (m *AttestationParams) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

// ServiceParams
type ServiceParams struct {
	Storage     []StorageParams     `protobuf:"bytes,1,rep,name=storage,proto3" json:"storage" yaml:"storage"`
	Credentials *ImageCredentials   `protobuf:"bytes,10,opt,name=credentials,proto3" json:"credentials,omitempty" yaml:"credentials,omitempty"`
	Permissions *ServicePermissions `protobuf:"bytes,11,opt,name=permissions,proto3" json:"permissions,omitempty" yaml:"permissions,omitempty"`
	Attestation *AttestationParams  `protobuf:"bytes,12,opt,name=attestation,proto3" json:"attestation,omitempty" yaml:"attestation,omitempty"`
}

func (m *ServiceParams) Reset()      { *m = ServiceParams{} }
func (*ServiceParams) ProtoMessage() {}
func (*ServiceParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d5964c4976d68e5, []int{3}
}
func (m *ServiceParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ServiceParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ServiceParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ServiceParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceParams.Merge(m, src)
}
func (m *ServiceParams) XXX_Size() int {
	return m.Size()
}
func (m *ServiceParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceParams.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceParams proto.InternalMessageInfo

func (m *ServiceParams) GetStorage() []StorageParams {
	if m != nil {
		return m.Storage
	}
	return nil
}

func (m *ServiceParams) GetCredentials() *ImageCredentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *ServiceParams) GetPermissions() *ServicePermissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *ServiceParams) GetAttestation() *AttestationParams {
	if m != nil {
		return m.Attestation
	}
	return nil
}

// Credentials to fetch image from registry
type ImageCredentials struct {
	Host     string `protobuf:"bytes,1,opt,name=host,proto3" json:"host" yaml:"host"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email" yaml:"email"`
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username" yaml:"username"`
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password" yaml:"password"`
}

func (m *ImageCredentials) Reset()      { *m = ImageCredentials{} }
func (*ImageCredentials) ProtoMessage() {}
func (*ImageCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d5964c4976d68e5, []int{4}
}
func (m *ImageCredentials) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ImageCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ImageCredentials.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ImageCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageCredentials.Merge(m, src)
}
func (m *ImageCredentials) XXX_Size() int {
	return m.Size()
}
func (m *ImageCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_ImageCredentials proto.InternalMessageInfo

func (m *ImageCredentials) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ImageCredentials) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ImageCredentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ImageCredentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// Service stores name, image, args, env, unit, count and expose list of service
type Service struct {
	Name        string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name" yaml:"name"`
	Image       string            `protobuf:"bytes,2,opt,name=image,proto3" json:"image" yaml:"image"`
	Command     []string          `protobuf:"bytes,3,rep,name=command,proto3" json:"command" yaml:"command"`
	Args        []string          `protobuf:"bytes,4,rep,name=args,proto3" json:"args" yaml:"args"`
	Env         []string          `protobuf:"bytes,5,rep,name=env,proto3" json:"env" yaml:"env"`
	Resources   v1beta4.Resources `protobuf:"bytes,6,opt,name=resources,proto3" json:"resources" yaml:"resources"`
	Count       uint32            `protobuf:"varint,7,opt,name=count,proto3" json:"count" yaml:"count"`
	Expose      ServiceExposes    `protobuf:"bytes,8,rep,name=expose,proto3,castrepeated=ServiceExposes" json:"expose" yaml:"expose"`
	Params      *ServiceParams    `protobuf:"bytes,9,opt,name=params,proto3" json:"params,omitempty" yaml:"params,omitempty"`
	Credentials *ImageCredentials `protobuf:"bytes,10,opt,name=credentials,proto3" json:"credentials" yaml:"credentials"`
}

func (m *Service) Reset()      { *m = Service{} }
func (*Service) ProtoMessage() {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d5964c4976d68e5, []int{5}
}
func (m *Service) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Service.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return m.Size()
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Service) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *Service) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Service) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *Service) GetResources() v1beta4.Resources {
	if m != nil {
		return m.Resources
	}
	return v1beta4.Resources{}
}

func (m *Service) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Service) GetExpose() ServiceExposes {
	if m != nil {
		return m.Expose
	}
	return nil
}

func (m *Service) GetParams() *ServiceParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Service) GetCredentials() *ImageCredentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func init() {
	proto.RegisterType((*StorageParams)(nil), "akash.manifest.v2beta3.StorageParams")
	proto.RegisterType((*ServicePermissions)(nil), "akash.manifest.v2beta3.ServicePermissions")
	proto.RegisterType((*AttestationParams)(nil), "akash.manifest.v2beta3.AttestationParams")
	proto.RegisterType((*ServiceParams)(nil), "akash.manifest.v2beta3.ServiceParams")
	proto.RegisterType((*ImageCredentials)(nil), "akash.manifest.v2beta3.ImageCredentials")
	proto.RegisterType((*Service)(nil), "akash.manifest.v2beta3.Service")
}

func init() {
	proto.RegisterFile("akash/manifest/v2beta3/service.proto", fileDescriptor_6d5964c4976d68e5)
}

var fileDescriptor_6d5964c4976d68e5 = []byte{
	// 876 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcf, 0x6f, 0x23, 0x35,
	0x14, 0x8e, 0x49, 0xda, 0xa6, 0xce, 0xb6, 0x14, 0x8b, 0x65, 0x67, 0x2b, 0x88, 0x83, 0xc5, 0x8a,
	0xec, 0x76, 0x35, 0xd1, 0xb6, 0x48, 0x48, 0xfc, 0x10, 0xda, 0x41, 0x1c, 0x90, 0x90, 0x58, 0x79,
	0xc5, 0x85, 0x0b, 0x72, 0x12, 0x93, 0x1d, 0x35, 0x33, 0x8e, 0xc6, 0xd3, 0x40, 0x6f, 0x5c, 0x81,
	0x0b, 0x67, 0xfe, 0x04, 0xf8, 0x47, 0x7a, 0xdc, 0xe3, 0x9e, 0x0c, 0xb4, 0xb7, 0x1c, 0x73, 0xe0,
	0x8c, 0xfc, 0xec, 0xa9, 0x27, 0x34, 0xa5, 0x42, 0x7b, 0x4a, 0xde, 0xf7, 0x7e, 0xfa, 0xd9, 0xdf,
	0x37, 0xf8, 0x1d, 0x71, 0x2c, 0xf4, 0xb3, 0x41, 0x26, 0xf2, 0xf4, 0x5b, 0xa9, 0xcb, 0xc1, 0xfc,
	0x70, 0x28, 0x4b, 0x71, 0x34, 0xd0, 0xb2, 0x98, 0xa7, 0x23, 0x19, 0xcf, 0x0a, 0x55, 0x2a, 0xf2,
	0x06, 0x44, 0xc5, 0x55, 0x54, 0xec, 0xa3, 0xf6, 0x5f, 0x9f, 0xa8, 0x89, 0x82, 0x90, 0x81, 0xfd,
	0xe7, 0xa2, 0xf7, 0x1f, 0xfc, 0x77, 0x4d, 0xf9, 0xfd, 0x4c, 0x69, 0x5f, 0x79, 0xff, 0xa1, 0x8b,
	0x1d, 0x0a, 0x2d, 0x07, 0x85, 0xd4, 0xea, 0xa4, 0x18, 0x49, 0x3d, 0x98, 0x3f, 0xb2, 0x19, 0xef,
	0x05, 0xc4, 0x45, 0xb3, 0xdf, 0x11, 0xde, 0x79, 0x5a, 0xaa, 0x42, 0x4c, 0xe4, 0x13, 0x51, 0x88,
	0x4c, 0x93, 0x03, 0xdc, 0xca, 0x45, 0x26, 0x23, 0xd4, 0x43, 0xfd, 0xed, 0xe4, 0xce, 0xc2, 0x50,
	0xb0, 0x97, 0x86, 0x76, 0x4e, 0x45, 0x36, 0xfd, 0x80, 0x59, 0x8b, 0x71, 0x00, 0xc9, 0x00, 0x6f,
	0x64, 0xea, 0x24, 0x2f, 0xa3, 0x57, 0x20, 0xfa, 0xee, 0xc2, 0x50, 0x07, 0x2c, 0x0d, 0xbd, 0xe5,
	0xc2, 0xc1, 0x64, 0xdc, 0xc1, 0xe4, 0x23, 0xbc, 0x5d, 0x48, 0x31, 0xfe, 0x46, 0xe5, 0xd3, 0xd3,
	0xa8, 0xd9, 0x43, 0xfd, 0x76, 0x42, 0x17, 0x86, 0xb6, 0x2d, 0xf8, 0x65, 0x3e, 0x3d, 0x5d, 0x1a,
	0xfa, 0xaa, 0xcb, 0xab, 0x10, 0xc6, 0x2f, 0x9d, 0xec, 0x2b, 0x4c, 0x9e, 0xba, 0x23, 0x3f, 0x91,
	0x45, 0x96, 0x6a, 0x9d, 0xaa, 0x5c, 0x93, 0x4f, 0x70, 0xcb, 0x46, 0x44, 0xa8, 0xd7, 0xec, 0x6f,
	0x27, 0x07, 0x0b, 0x43, 0x77, 0xad, 0xfd, 0x50, 0x65, 0x69, 0x29, 0xb3, 0x59, 0x69, 0x8b, 0xde,
	0x0e, 0x45, 0x03, 0xce, 0x38, 0x24, 0xb2, 0x2f, 0xf0, 0x6b, 0x8f, 0xcb, 0x52, 0xea, 0x52, 0x94,
	0xa9, 0xca, 0xfd, 0x1e, 0xde, 0xc7, 0x5b, 0x32, 0x17, 0xc3, 0xa9, 0x1c, 0xc3, 0x2a, 0xda, 0xc9,
	0x5b, 0x0b, 0x43, 0x2b, 0x68, 0x69, 0xe8, 0xae, 0xab, 0xe8, 0x01, 0xc6, 0x2b, 0x17, 0xfb, 0xb5,
	0x85, 0x77, 0xaa, 0x29, 0x5d, 0xa9, 0x21, 0xde, 0xd2, 0x6e, 0xc7, 0x30, 0x63, 0xe7, 0xf0, 0x5e,
	0xbc, 0xfe, 0xfa, 0xe3, 0x95, 0xab, 0x48, 0xde, 0x3e, 0x33, 0xb4, 0x61, 0xbb, 0xfa, 0xec, 0xd0,
	0xd5, 0x03, 0x8c, 0x57, 0x2e, 0xf2, 0x23, 0xc2, 0x9d, 0x51, 0x21, 0xc7, 0x32, 0x2f, 0x53, 0x31,
	0xd5, 0x11, 0xee, 0xa1, 0x7e, 0xe7, 0xb0, 0x7f, 0x5d, 0xa3, 0xcf, 0x33, 0x31, 0x91, 0x9f, 0x86,
	0xf8, 0xe4, 0xe3, 0x33, 0x43, 0xd1, 0xc2, 0xd0, 0xdb, 0xb5, 0x22, 0x2b, 0x1b, 0x7c, 0xd3, 0x75,
	0x5e, 0xeb, 0x66, 0xbc, 0xde, 0x9b, 0xfc, 0x8c, 0x70, 0x67, 0x16, 0x2e, 0x28, 0xea, 0xc0, 0x2c,
	0x0f, 0xae, 0x3d, 0xf4, 0x95, 0x2b, 0x0d, 0xd3, 0xd4, 0xca, 0xac, 0x9b, 0x66, 0xad, 0x9b, 0xf1,
	0x7a, 0x77, 0xf2, 0x13, 0xc2, 0x1d, 0x11, 0xae, 0x37, 0xba, 0x05, 0xd3, 0xdc, 0xbf, 0x6e, 0x9a,
	0x2b, 0x2f, 0x21, 0x0c, 0x53, 0xab, 0xb2, 0x6e, 0x98, 0xb5, 0x6e, 0xc6, 0xeb, 0xcd, 0xd9, 0x02,
	0xe1, 0xbd, 0x7f, 0xef, 0xde, 0x52, 0xee, 0x99, 0xd2, 0x65, 0x9d, 0x72, 0xd6, 0x0e, 0x94, 0xb3,
	0x16, 0xe3, 0x00, 0x5a, 0xca, 0xc9, 0x4c, 0xa4, 0xd3, 0x3a, 0xe5, 0x00, 0x08, 0x94, 0x03, 0x93,
	0x71, 0x07, 0x93, 0x0f, 0x71, 0xfb, 0x44, 0xcb, 0x02, 0x48, 0xdd, 0x84, 0x1c, 0x60, 0x5c, 0x85,
	0x05, 0xc6, 0x55, 0x08, 0xe3, 0x97, 0x4e, 0x9b, 0x3c, 0x13, 0x5a, 0x7f, 0xa7, 0x8a, 0x71, 0xd4,
	0x0a, 0xc9, 0x15, 0x16, 0x92, 0x2b, 0x84, 0xf1, 0x4b, 0x27, 0xfb, 0x7b, 0x03, 0x6f, 0xf9, 0xcb,
	0xfd, 0xdf, 0xb2, 0x92, 0xda, 0x25, 0xd5, 0xcf, 0x08, 0x40, 0x38, 0x23, 0x98, 0x8c, 0x3b, 0xd8,
	0x92, 0x75, 0xa4, 0xb2, 0x4c, 0xe4, 0xe3, 0xa8, 0x09, 0x2a, 0x00, 0x64, 0xf5, 0x50, 0xa0, 0x8d,
	0x07, 0x18, 0xaf, 0x5c, 0x76, 0x2c, 0x51, 0x4c, 0x74, 0xd4, 0x82, 0x2c, 0x18, 0xcb, 0xda, 0x61,
	0x2c, 0x6b, 0x31, 0x0e, 0x20, 0x39, 0xc0, 0x4d, 0x99, 0xcf, 0xa3, 0x0d, 0x88, 0xbd, 0xeb, 0x5f,
	0x85, 0x85, 0x96, 0x86, 0xe2, 0x4a, 0x0e, 0xe6, 0x8c, 0x5b, 0x88, 0x4c, 0xad, 0xd2, 0x79, 0xb1,
	0x8d, 0x36, 0xe1, 0xcd, 0xbd, 0xeb, 0xdf, 0x9c, 0xd5, 0xe6, 0x38, 0x28, 0xb1, 0xd7, 0xe6, 0x98,
	0x57, 0x48, 0x72, 0xcf, 0x13, 0x3f, 0x54, 0x58, 0x1a, 0xba, 0x57, 0x49, 0x98, 0x87, 0x18, 0x0f,
	0x6e, 0xbb, 0xb1, 0x11, 0x08, 0xf1, 0x56, 0x0f, 0xf5, 0x77, 0xdc, 0xc6, 0x46, 0xab, 0x42, 0x3c,
	0xf2, 0x42, 0x0c, 0xbf, 0x64, 0x86, 0x37, 0xdd, 0x67, 0x23, 0x6a, 0xdf, 0x20, 0x49, 0xee, 0x02,
	0x3f, 0x83, 0xe0, 0xe4, 0x91, 0x9f, 0xcc, 0x27, 0x2f, 0x0d, 0xdd, 0xf1, 0x07, 0x07, 0x9b, 0xfd,
	0xf6, 0x07, 0xdd, 0x5d, 0xc9, 0xd0, 0xdc, 0x87, 0x92, 0x02, 0x6f, 0xce, 0x80, 0x50, 0xd1, 0x36,
	0x6c, 0xe3, 0xa6, 0x8e, 0x9e, 0x7d, 0x47, 0x7e, 0xcf, 0x7b, 0x2e, 0x79, 0x85, 0x78, 0x77, 0xaa,
	0xb7, 0xb7, 0xea, 0x61, 0xdc, 0x77, 0x22, 0x27, 0x2f, 0x27, 0x8a, 0xf7, 0x7d, 0xef, 0x7a, 0x91,
	0xa5, 0xa1, 0xe4, 0x8a, 0x14, 0xae, 0x0a, 0x60, 0xf2, 0xf8, 0xc5, 0x5f, 0xdd, 0xc6, 0x0f, 0xe7,
	0x5d, 0x74, 0x76, 0xde, 0x45, 0xcf, 0xcf, 0xbb, 0xe8, 0xcf, 0xf3, 0x2e, 0xfa, 0xe5, 0xa2, 0xdb,
	0x78, 0x7e, 0xd1, 0x6d, 0xbc, 0xb8, 0xe8, 0x36, 0xbe, 0xa6, 0xb3, 0xe3, 0x49, 0x2c, 0x8e, 0xcb,
	0x78, 0x2c, 0xe7, 0x83, 0x89, 0xba, 0xf2, 0x69, 0x1f, 0x6e, 0xc2, 0xf7, 0xf9, 0xe8, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x8b, 0xb9, 0x3c, 0x7e, 0x4f, 0x08, 0x00, 0x00,
}

func (m *StorageParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StorageParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StorageParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ReadOnly {
		i--
		if m.ReadOnly {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Mount) > 0 {
		i -= len(m.Mount)
		copy(dAtA[i:], m.Mount)
		i = encodeVarintService(dAtA, i, uint64(len(m.Mount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintService(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ServicePermissions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ServicePermissions) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ServicePermissions) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Read) > 0 {
		for iNdEx := len(m.Read) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Read[iNdEx])
			copy(dAtA[i:], m.Read[iNdEx])
			i = encodeVarintService(dAtA, i, uint64(len(m.Read[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *AttestationParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AttestationParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AttestationParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ServiceParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ServiceParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ServiceParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Attestation != nil {
		{
			size, err := m.Attestation.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintService(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x62
	}
	if m.Permissions != nil {
		{
			size, err := m.Permissions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintService(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	if m.Credentials != nil {
		{
			size, err := m.Credentials.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintService(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x52
	}
	if len(m.Storage) > 0 {
		for iNdEx := len(m.Storage) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Storage[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintService(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ImageCredentials) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ImageCredentials) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ImageCredentials) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Password) > 0 {
		i -= len(m.Password)
		copy(dAtA[i:], m.Password)
		i = encodeVarintService(dAtA, i, uint64(len(m.Password)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintService(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Email) > 0 {
		i -= len(m.Email)
		copy(dAtA[i:], m.Email)
		i = encodeVarintService(dAtA, i, uint64(len(m.Email)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Host) > 0 {
		i -= len(m.Host)
		copy(dAtA[i:], m.Host)
		i = encodeVarintService(dAtA, i, uint64(len(m.Host)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Service) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Service) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Service) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Credentials != nil {
		{
			size, err := m.Credentials.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintService(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x52
	}
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintService(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Expose) > 0 {
		for iNdEx := len(m.Expose) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Expose[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintService(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if m.Count != 0 {
		i = encodeVarintService(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x38
	}
	{
		size, err := m.Resources.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintService(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.Env) > 0 {
		for iNdEx := len(m.Env) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Env[iNdEx])
			copy(dAtA[i:], m.Env[iNdEx])
			i = encodeVarintService(dAtA, i, uint64(len(m.Env[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Args) > 0 {
		for iNdEx := len(m.Args) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Args[iNdEx])
			copy(dAtA[i:], m.Args[iNdEx])
			i = encodeVarintService(dAtA, i, uint64(len(m.Args[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Command) > 0 {
		for iNdEx := len(m.Command) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Command[iNdEx])
			copy(dAtA[i:], m.Command[iNdEx])
			i = encodeVarintService(dAtA, i, uint64(len(m.Command[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Image) > 0 {
		i -= len(m.Image)
		copy(dAtA[i:], m.Image)
		i = encodeVarintService(dAtA, i, uint64(len(m.Image)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintService(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintService(dAtA []byte, offset int, v uint64) int {
	offset -= sovService(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StorageParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	l = len(m.Mount)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	if m.ReadOnly {
		n += 2
	}
	return n
}

func (m *ServicePermissions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Read) > 0 {
		for _, s := range m.Read {
			l = len(s)
			n += 1 + l + sovService(uint64(l))
		}
	}
	return n
}

func (m *AttestationParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Enabled {
		n += 2
	}
	return n
}

func (m *ServiceParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Storage) > 0 {
		for _, e := range m.Storage {
			l = e.Size()
			n += 1 + l + sovService(uint64(l))
		}
	}
	if m.Credentials != nil {
		l = m.Credentials.Size()
		n += 1 + l + sovService(uint64(l))
	}
	if m.Permissions != nil {
		l = m.Permissions.Size()
		n += 1 + l + sovService(uint64(l))
	}
	if m.Attestation != nil {
		l = m.Attestation.Size()
		n += 1 + l + sovService(uint64(l))
	}
	return n
}

func (m *ImageCredentials) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Host)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	l = len(m.Email)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	l = len(m.Password)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	return n
}

func (m *Service) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	l = len(m.Image)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	if len(m.Command) > 0 {
		for _, s := range m.Command {
			l = len(s)
			n += 1 + l + sovService(uint64(l))
		}
	}
	if len(m.Args) > 0 {
		for _, s := range m.Args {
			l = len(s)
			n += 1 + l + sovService(uint64(l))
		}
	}
	if len(m.Env) > 0 {
		for _, s := range m.Env {
			l = len(s)
			n += 1 + l + sovService(uint64(l))
		}
	}
	l = m.Resources.Size()
	n += 1 + l + sovService(uint64(l))
	if m.Count != 0 {
		n += 1 + sovService(uint64(m.Count))
	}
	if len(m.Expose) > 0 {
		for _, e := range m.Expose {
			l = e.Size()
			n += 1 + l + sovService(uint64(l))
		}
	}
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovService(uint64(l))
	}
	if m.Credentials != nil {
		l = m.Credentials.Size()
		n += 1 + l + sovService(uint64(l))
	}
	return n
}

func sovService(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozService(x uint64) (n int) {
	return sovService(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *StorageParams) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&StorageParams{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Mount:` + fmt.Sprintf("%v", this.Mount) + `,`,
		`ReadOnly:` + fmt.Sprintf("%v", this.ReadOnly) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ServicePermissions) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ServicePermissions{`,
		`Read:` + fmt.Sprintf("%v", this.Read) + `,`,
		`}`,
	}, "")
	return s
}
func (this *AttestationParams) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AttestationParams{`,
		`Enabled:` + fmt.Sprintf("%v", this.Enabled) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ServiceParams) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForStorage := "[]StorageParams{"
	for _, f := range this.Storage {
		repeatedStringForStorage += strings.Replace(strings.Replace(f.String(), "StorageParams", "StorageParams", 1), `&`, ``, 1) + ","
	}
	repeatedStringForStorage += "}"
	s := strings.Join([]string{`&ServiceParams{`,
		`Storage:` + repeatedStringForStorage + `,`,
		`Credentials:` + strings.Replace(this.Credentials.String(), "ImageCredentials", "ImageCredentials", 1) + `,`,
		`Permissions:` + strings.Replace(this.Permissions.String(), "ServicePermissions", "ServicePermissions", 1) + `,`,
		`Attestation:` + strings.Replace(this.Attestation.String(), "AttestationParams", "AttestationParams", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ImageCredentials) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ImageCredentials{`,
		`Host:` + fmt.Sprintf("%v", this.Host) + `,`,
		`Email:` + fmt.Sprintf("%v", this.Email) + `,`,
		`Username:` + fmt.Sprintf("%v", this.Username) + `,`,
		`Password:` + fmt.Sprintf("%v", this.Password) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Service) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForExpose := "[]ServiceExpose{"
	for _, f := range this.Expose {
		repeatedStringForExpose += fmt.Sprintf("%v", f) + ","
	}
	repeatedStringForExpose += "}"
	s := strings.Join([]string{`&Service{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Image:` + fmt.Sprintf("%v", this.Image) + `,`,
		`Command:` + fmt.Sprintf("%v", this.Command) + `,`,
		`Args:` + fmt.Sprintf("%v", this.Args) + `,`,
		`Env:` + fmt.Sprintf("%v", this.Env) + `,`,
		`Resources:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Resources), "Resources", "v1beta4.Resources", 1), `&`, ``, 1) + `,`,
		`Count:` + fmt.Sprintf("%v", this.Count) + `,`,
		`Expose:` + repeatedStringForExpose + `,`,
		`Params:` + strings.Replace(this.Params.String(), "ServiceParams", "ServiceParams", 1) + `,`,
		`Credentials:` + strings.Replace(this.Credentials.String(), "ImageCredentials", "ImageCredentials", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringService(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *StorageParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StorageParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StorageParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReadOnly", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ReadOnly = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ServicePermissions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ServicePermissions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ServicePermissions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Read", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Read = append(m.Read, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AttestationParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AttestationParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AttestationParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ServiceParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ServiceParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ServiceParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Storage", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Storage = append(m.Storage, StorageParams{})
			if err := m.Storage[len(m.Storage)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Credentials", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Credentials == nil {
				m.Credentials = &ImageCredentials{}
			}
			if err := m.Credentials.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Permissions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Permissions == nil {
				m.Permissions = &ServicePermissions{}
			}
			if err := m.Permissions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attestation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Attestation == nil {
				m.Attestation = &AttestationParams{}
			}
			if err := m.Attestation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ImageCredentials) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ImageCredentials: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ImageCredentials: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Host", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Host = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Email", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Email = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Password", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Password = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Service) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Service: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Service: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Image", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Image = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Command", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Command = append(m.Command, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Args", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Args = append(m.Args, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Env", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Env = append(m.Env, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Resources", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Resources.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expose", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Expose = append(m.Expose, ServiceExpose{})
			if err := m.Expose[len(m.Expose)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &ServiceParams{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Credentials", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Credentials == nil {
				m.Credentials = &ImageCredentials{}
			}
			if err := m.Credentials.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipService(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowService
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthService
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupService
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthService
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthService        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowService          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupService = fmt.Errorf("proto: unexpected end of group")
)
