// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/discovery/v1/akash.proto

package client

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Akash akash specific RPC parameters.
type Akash struct {
	// ClientInfo holds information about the client.
	// Kept for backward compatibility. New clients should use supported_versions.
	ClientInfo ClientInfo `protobuf:"bytes,1,opt,name=client_info,json=clientInfo,proto3" json:"client_info" yaml:"client_info"`
	// SupportedVersions lists all API versions the node supports.
	// Clients should pick the best match from this list.
	SupportedVersions []VersionInfo `protobuf:"bytes,2,rep,name=supported_versions,json=supportedVersions,proto3" json:"supported_versions" yaml:"supported_versions"`
	// ChainID is the identifier of the blockchain network.
	ChainID string `protobuf:"bytes,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id" yaml:"chain_id"`
	// NodeVersion is the software version of the node.
	NodeVersion string `protobuf:"bytes,4,opt,name=node_version,json=nodeVersion,proto3" json:"node_version" yaml:"node_version"`
	// MinClientVersion is the minimum client version the node accepts.
	MinClientVersion string `protobuf:"bytes,5,opt,name=min_client_version,json=minClientVersion,proto3" json:"min_client_version" yaml:"min_client_version"`
}

func (m *Akash) Reset()         { *m = Akash{} }
func (m *Akash) String() string { return proto.CompactTextString(m) }
func (*Akash) ProtoMessage()    {}
func (*Akash) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf31dd3d85bbd20d, []int{0}
}
func (m *Akash) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Akash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Akash.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Akash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Akash.Merge(m, src)
}
func (m *Akash) XXX_Size() int {
	return m.Size()
}
func (m *Akash) XXX_DiscardUnknown() {
	xxx_messageInfo_Akash.DiscardUnknown(m)
}

var xxx_messageInfo_Akash proto.InternalMessageInfo

func (m *Akash) GetClientInfo() ClientInfo {
	if m != nil {
		return m.ClientInfo
	}
	return ClientInfo{}
}

func (m *Akash) GetSupportedVersions() []VersionInfo {
	if m != nil {
		return m.SupportedVersions
	}
	return nil
}

func (m *Akash) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *Akash) GetNodeVersion() string {
	if m != nil {
		return m.NodeVersion
	}
	return ""
}

func (m *Akash) GetMinClientVersion() string {
	if m != nil {
		return m.MinClientVersion
	}
	return ""
}

func init() {
	proto.RegisterType((*Akash)(nil), "akash.discovery.v1.Akash")
}

func init() { proto.RegisterFile("akash/discovery/v1/akash.proto", fileDescriptor_bf31dd3d85bbd20d) }

var fileDescriptor_bf31dd3d85bbd20d = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xb1, 0xef, 0x93, 0x40,
	0x14, 0x06, 0xdb, 0x5a, 0x3d, 0x4c, 0xb4, 0xa7, 0x03, 0x76, 0xb8, 0x6b, 0x88, 0x89, 0x8d, 0x03,
	0xa4, 0xad, 0x89, 0x89, 0x9b, 0xad, 0x0e, 0x35, 0x4e, 0x98, 0x38, 0xb8, 0x10, 0x04, 0x4a, 0x2f,
	0x6d, 0xef, 0x08, 0x20, 0xb1, 0xff, 0x85, 0x93, 0x93, 0x7f, 0x50, 0xc7, 0x8e, 0x4e, 0x17, 0x43,
	0x37, 0x46, 0xfe, 0x02, 0xc3, 0x71, 0x6d, 0xf1, 0x47, 0xb7, 0x77, 0xdf, 0xf7, 0xbe, 0xef, 0x7d,
	0x0f, 0x1e, 0x40, 0xee, 0xc6, 0x4d, 0xd6, 0x96, 0x4f, 0x12, 0x8f, 0x65, 0x41, 0xbc, 0xb7, 0xb2,
	0x89, 0x25, 0x20, 0x33, 0x8a, 0x59, 0xca, 0x20, 0xac, 0x1f, 0x17, 0xde, 0xcc, 0x26, 0xc3, 0x17,
	0x37, 0x34, 0xde, 0x96, 0x04, 0x34, 0x75, 0x08, 0x5d, 0xb1, 0x5a, 0x39, 0x7c, 0x16, 0xb2, 0x90,
	0x89, 0xd2, 0xaa, 0xaa, 0x1a, 0x35, 0x7e, 0x75, 0x41, 0xef, 0x5d, 0x25, 0x87, 0x3f, 0x80, 0xd6,
	0x10, 0xe9, 0xea, 0x48, 0x1d, 0x6b, 0x53, 0x64, 0xb6, 0xe7, 0x99, 0x0b, 0xd1, 0xb6, 0xa4, 0x2b,
	0x36, 0x7f, 0x73, 0xe0, 0x58, 0xc9, 0x39, 0x06, 0x57, 0xac, 0xe0, 0xb8, 0x69, 0x54, 0x72, 0x0c,
	0xf7, 0xee, 0x6e, 0xfb, 0xd6, 0x68, 0x80, 0x86, 0x0d, 0xbc, 0x8b, 0x00, 0xfe, 0x56, 0x01, 0x4c,
	0xbe, 0x47, 0x11, 0x8b, 0xd3, 0xc0, 0x77, 0xb2, 0x20, 0x4e, 0x08, 0xa3, 0x89, 0x7e, 0x6f, 0xd4,
	0x19, 0x6b, 0x53, 0x7c, 0x2b, 0xc1, 0x97, 0xba, 0x47, 0x44, 0xf8, 0x24, 0x23, 0x0c, 0x3e, 0x9f,
	0x2d, 0x24, 0x9b, 0x14, 0x1c, 0xdf, 0xf0, 0x2d, 0x39, 0x7e, 0x5e, 0x07, 0x6a, 0x73, 0x86, 0x3d,
	0x48, 0xee, 0xba, 0xc0, 0x0f, 0xe0, 0x81, 0xb7, 0x76, 0x09, 0x75, 0x88, 0xaf, 0x77, 0x46, 0xea,
	0xf8, 0xe1, 0xfc, 0x55, 0xce, 0x71, 0x7f, 0x51, 0x61, 0xcb, 0xf7, 0x05, 0xc7, 0x17, 0xba, 0xe4,
	0xf8, 0xb1, 0xdc, 0x55, 0x22, 0x86, 0xdd, 0x17, 0xe5, 0xd2, 0x87, 0x1f, 0xc1, 0x23, 0xca, 0xfc,
	0xe0, 0x3c, 0x4b, 0xef, 0x0a, 0xab, 0x97, 0x05, 0xc7, 0xff, 0xe1, 0x25, 0xc7, 0x4f, 0x6b, 0x8f,
	0x26, 0x6a, 0xd8, 0x5a, 0xf5, 0x94, 0x99, 0xa0, 0x0b, 0xe0, 0x8e, 0x50, 0x47, 0x7e, 0xd1, 0xb3,
	0x63, 0x4f, 0x38, 0xce, 0xaa, 0xb5, 0xdb, 0xec, 0x75, 0xed, 0x36, 0x67, 0xd8, 0x4f, 0x76, 0x84,
	0xd6, 0xbf, 0x50, 0x8e, 0x98, 0xbf, 0x3e, 0xe4, 0x48, 0x3d, 0xe6, 0x48, 0xfd, 0x9b, 0x23, 0xf5,
	0xe7, 0x09, 0x29, 0xc7, 0x13, 0x52, 0xfe, 0x9c, 0x90, 0xf2, 0x75, 0x18, 0x6d, 0x42, 0xd3, 0xdd,
	0xa4, 0xa6, 0x1f, 0x64, 0x56, 0xc8, 0xac, 0x2a, 0x98, 0xbc, 0xb7, 0x6f, 0xf7, 0xc5, 0x55, 0xcd,
	0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xed, 0x98, 0xc3, 0x3e, 0xc7, 0x02, 0x00, 0x00,
}

func (m *Akash) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Akash) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Akash) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MinClientVersion) > 0 {
		i -= len(m.MinClientVersion)
		copy(dAtA[i:], m.MinClientVersion)
		i = encodeVarintAkash(dAtA, i, uint64(len(m.MinClientVersion)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.NodeVersion) > 0 {
		i -= len(m.NodeVersion)
		copy(dAtA[i:], m.NodeVersion)
		i = encodeVarintAkash(dAtA, i, uint64(len(m.NodeVersion)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ChainID) > 0 {
		i -= len(m.ChainID)
		copy(dAtA[i:], m.ChainID)
		i = encodeVarintAkash(dAtA, i, uint64(len(m.ChainID)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SupportedVersions) > 0 {
		for iNdEx := len(m.SupportedVersions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SupportedVersions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAkash(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ClientInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintAkash(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintAkash(dAtA []byte, offset int, v uint64) int {
	offset -= sovAkash(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Akash) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ClientInfo.Size()
	n += 1 + l + sovAkash(uint64(l))
	if len(m.SupportedVersions) > 0 {
		for _, e := range m.SupportedVersions {
			l = e.Size()
			n += 1 + l + sovAkash(uint64(l))
		}
	}
	l = len(m.ChainID)
	if l > 0 {
		n += 1 + l + sovAkash(uint64(l))
	}
	l = len(m.NodeVersion)
	if l > 0 {
		n += 1 + l + sovAkash(uint64(l))
	}
	l = len(m.MinClientVersion)
	if l > 0 {
		n += 1 + l + sovAkash(uint64(l))
	}
	return n
}

func sovAkash(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAkash(x uint64) (n int) {
	return sovAkash(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Akash) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAkash
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Akash: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Akash: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAkash
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAkash
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAkash
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ClientInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupportedVersions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAkash
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAkash
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAkash
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SupportedVersions = append(m.SupportedVersions, VersionInfo{})
			if err := m.SupportedVersions[len(m.SupportedVersions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAkash
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAkash
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAkash
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAkash
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAkash
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAkash
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinClientVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAkash
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAkash
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAkash
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinClientVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAkash(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAkash
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAkash(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAkash
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAkash
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAkash
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAkash
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAkash
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAkash
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAkash        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAkash          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAkash = fmt.Errorf("proto: unexpected end of group")
)
