// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/deployment/v1beta5/resourceunit.proto

package v1beta5

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	v1beta4 "pkg.akt.dev/go/node/types/resources/v1beta4"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ResourceUnit extends Resources and adds Count along with the Price.
type ResourceUnit struct {
	// Resource holds the amount of resources.
	v1beta4.Resources `protobuf:"bytes,1,opt,name=resource,proto3,embedded=resource" json:"resource" yaml:"resource"`
	// Count corresponds to the amount of replicas to run of the resources.
	Count uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count" yaml:"count"`
	// Price holds the pricing for the resource units.
	Prices github_com_cosmos_cosmos_sdk_types.DecCoins `protobuf:"bytes,3,rep,name=prices,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.DecCoins" json:"prices" yaml:"prices"`
}

func (m *ResourceUnit) Reset()         { *m = ResourceUnit{} }
func (m *ResourceUnit) String() string { return proto.CompactTextString(m) }
func (*ResourceUnit) ProtoMessage()    {}
func (*ResourceUnit) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b3ca189685a0e0e, []int{0}
}
func (m *ResourceUnit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResourceUnit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResourceUnit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResourceUnit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceUnit.Merge(m, src)
}
func (m *ResourceUnit) XXX_Size() int {
	return m.Size()
}
func (m *ResourceUnit) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceUnit.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceUnit proto.InternalMessageInfo

func (m *ResourceUnit) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ResourceUnit) GetPrices() github_com_cosmos_cosmos_sdk_types.DecCoins {
	if m != nil {
		return m.Prices
	}
	return nil
}

func init() {
	proto.RegisterType((*ResourceUnit)(nil), "akash.deployment.v1beta5.ResourceUnit")
}

func init() {
	proto.RegisterFile("akash/deployment/v1beta5/resourceunit.proto", fileDescriptor_5b3ca189685a0e0e)
}

var fileDescriptor_5b3ca189685a0e0e = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x3f, 0x6e, 0xe2, 0x40,
	0x14, 0xc6, 0x3d, 0xb0, 0x8b, 0x56, 0x06, 0xb4, 0x92, 0xb5, 0x85, 0x17, 0xad, 0x3c, 0xc8, 0xc5,
	0x82, 0x44, 0x32, 0x23, 0x48, 0xd2, 0x50, 0x45, 0x4e, 0xea, 0x14, 0x96, 0xd2, 0xa4, 0xf3, 0x9f,
	0x91, 0xb1, 0x8c, 0x3d, 0x96, 0x67, 0x8c, 0x44, 0x9f, 0x03, 0xe4, 0x08, 0xa9, 0x73, 0x84, 0x9c,
	0x80, 0x92, 0x32, 0xd5, 0x24, 0x82, 0x26, 0xa2, 0xe4, 0x04, 0x11, 0x9e, 0x31, 0x34, 0xa9, 0xec,
	0xf7, 0xbd, 0xdf, 0xf7, 0xbd, 0xa7, 0x67, 0xeb, 0x23, 0x2f, 0xf1, 0xd8, 0x0c, 0x87, 0x24, 0x9f,
	0xd3, 0x65, 0x4a, 0x32, 0x8e, 0x17, 0x63, 0x9f, 0x70, 0xef, 0x0a, 0x17, 0x84, 0xd1, 0xb2, 0x08,
	0x48, 0x99, 0xc5, 0x1c, 0xe5, 0x05, 0xe5, 0xd4, 0x30, 0x2b, 0x18, 0x9d, 0x60, 0xa4, 0xe0, 0xde,
	0x9f, 0x88, 0x46, 0xb4, 0x82, 0xf0, 0xe1, 0x4d, 0xf2, 0x3d, 0x2b, 0xa0, 0x2c, 0xa5, 0x0c, 0xfb,
	0x1e, 0x23, 0x2a, 0x77, 0x8c, 0x03, 0x1a, 0x67, 0xaa, 0x7f, 0x26, 0x87, 0x57, 0xed, 0x7a, 0x1c,
	0x53, 0xe0, 0xe5, 0x49, 0x91, 0xb4, 0xfd, 0xda, 0xd0, 0x3b, 0xae, 0xd2, 0xee, 0xb3, 0x98, 0x1b,
	0x73, 0xfd, 0x57, 0xcd, 0x98, 0xa0, 0x0f, 0x86, 0xed, 0xc9, 0x00, 0xc9, 0x0d, 0x0f, 0x89, 0xe8,
	0xe4, 0x57, 0x89, 0xa8, 0x76, 0x33, 0x67, 0xb0, 0x12, 0x50, 0x5b, 0x0b, 0x08, 0x76, 0x02, 0x1e,
	0x43, 0xf6, 0x02, 0xfe, 0x5e, 0x7a, 0xe9, 0x7c, 0x6a, 0xd7, 0x8a, 0xed, 0x1e, 0x9b, 0x06, 0xd6,
	0x7f, 0x06, 0xb4, 0xcc, 0xb8, 0xd9, 0xe8, 0x83, 0x61, 0xd7, 0xf9, 0xbb, 0x13, 0x50, 0x0a, 0x7b,
	0x01, 0x3b, 0xd2, 0x56, 0x95, 0xb6, 0x2b, 0x65, 0xe3, 0x11, 0xe8, 0xad, 0xbc, 0x88, 0x03, 0xc2,
	0xcc, 0x66, 0xbf, 0x39, 0x6c, 0x4f, 0xfe, 0x21, 0x79, 0x0f, 0xb9, 0x9e, 0xba, 0x07, 0xba, 0x25,
	0xc1, 0x0d, 0x8d, 0x33, 0xe7, 0xee, 0xb0, 0xd2, 0x4e, 0x40, 0xe5, 0xd9, 0x0b, 0xd8, 0x95, 0xa9,
	0xb2, 0xb6, 0x5f, 0xde, 0xe1, 0x28, 0x8a, 0xf9, 0xac, 0xf4, 0x51, 0x40, 0x53, 0xac, 0x4e, 0x2b,
	0x1f, 0xe7, 0x2c, 0x4c, 0x30, 0x5f, 0xe6, 0x84, 0xd5, 0x71, 0xcc, 0x55, 0x39, 0xd3, 0x1f, 0x9f,
	0xcf, 0x10, 0x38, 0xd7, 0xab, 0x8d, 0x05, 0xd6, 0x1b, 0x0b, 0x7c, 0x6c, 0x2c, 0xf0, 0xb4, 0xb5,
	0xb4, 0xf5, 0xd6, 0xd2, 0xde, 0xb6, 0x96, 0xf6, 0xf0, 0x3f, 0x4f, 0x22, 0xe4, 0x25, 0x1c, 0x85,
	0x64, 0x81, 0x23, 0x8a, 0x33, 0x1a, 0x92, 0x6f, 0xfe, 0x07, 0xbf, 0x55, 0x7d, 0x85, 0x8b, 0xaf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xa9, 0xd8, 0xd3, 0x9c, 0x32, 0x02, 0x00, 0x00,
}

func (this *ResourceUnit) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ResourceUnit)
	if !ok {
		that2, ok := that.(ResourceUnit)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Resources.Equal(&that1.Resources) {
		return false
	}
	if this.Count != that1.Count {
		return false
	}
	if len(this.Prices) != len(that1.Prices) {
		return false
	}
	for i := range this.Prices {
		if !this.Prices[i].Equal(&that1.Prices[i]) {
			return false
		}
	}
	return true
}
func (m *ResourceUnit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResourceUnit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResourceUnit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Prices) > 0 {
		for iNdEx := len(m.Prices) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Prices[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintResourceunit(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Count != 0 {
		i = encodeVarintResourceunit(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.Resources.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintResourceunit(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintResourceunit(dAtA []byte, offset int, v uint64) int {
	offset -= sovResourceunit(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ResourceUnit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Resources.Size()
	n += 1 + l + sovResourceunit(uint64(l))
	if m.Count != 0 {
		n += 1 + sovResourceunit(uint64(m.Count))
	}
	if len(m.Prices) > 0 {
		for _, e := range m.Prices {
			l = e.Size()
			n += 1 + l + sovResourceunit(uint64(l))
		}
	}
	return n
}

func sovResourceunit(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozResourceunit(x uint64) (n int) {
	return sovResourceunit(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ResourceUnit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowResourceunit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResourceUnit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResourceUnit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Resources", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResourceunit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthResourceunit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthResourceunit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Resources.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResourceunit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Prices", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResourceunit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthResourceunit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthResourceunit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Prices = append(m.Prices, types.DecCoin{})
			if err := m.Prices[len(m.Prices)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipResourceunit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthResourceunit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipResourceunit(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowResourceunit
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowResourceunit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowResourceunit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthResourceunit
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupResourceunit
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthResourceunit
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthResourceunit        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowResourceunit          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupResourceunit = fmt.Errorf("proto: unexpected end of group")
)
